<template><div class="stack">
<section class="card glass-panel header-card"><div class="header-info"><h2 class="card-title">{{ t.title }}</h2><p class="card-desc">{{ t.desc }}</p></div><button class="btn-primary" @click="saveAiSettings">{{ t.save }}</button></section>
<section class="card glass-panel card-pad stack"><div class="pill-row"><button v-for="p in providers" :key="p.value" class="btn-secondary" :class="{active:aiForm.provider===p.value}" @click="selectProvider(p.value)">{{ p.label }}</button></div><select v-model="aiForm.provider"><option v-for="p in providers" :key="p.value" :value="p.value">{{ p.label }}</option></select><input v-model="aiForm.baseUrl" :placeholder="t.baseUrl"/><input v-if="aiForm.provider!=='ollama'" v-model="aiForm.apiKey" type="password" :placeholder="t.apiKey"/><div class="action-grid two"><input v-model="aiForm.model" :placeholder="t.model"/><button class="btn-secondary" :disabled="busy.models" @click="fetchModels"><span v-if="busy.models" class="mini-spinner"></span>{{ t.models }}</button></div></section>
<section class="mobile-grid"><div class="card metric"><span>{{ t.batch }}</span><input v-model.number="aiForm.batchSize" type="number" min="1" max="200"/></div><div class="card metric"><span>{{ t.threads }}</span><input v-model.number="aiForm.concurrency" type="number" min="1" max="8"/></div><div class="card metric"><span>{{ t.interval }}</span><input v-model.number="aiForm.requestIntervalMs" type="number" min="0" max="60000"/></div><div class="card metric"><span>{{ t.retry }}</span><input v-model.number="aiForm.rateLimitRetries" type="number" min="0" max="10"/></div></section>
<section class="card glass-panel card-pad stack"><input v-model="aiForm.targetLang" :placeholder="t.target"/><textarea v-model="testSource" :placeholder="t.testSource"></textarea><button class="btn-primary" :disabled="busy.test" @click="testAi"><span v-if="busy.test" class="mini-spinner"></span>{{ t.test }}</button><div v-if="testResult" class="source-box">{{ testResult }}</div></section>
<section class="card glass-panel card-pad stack"><h3 class="card-title">{{ t.launch }}</h3><div class="mobile-grid"><label><span>{{ t.render }}</span><select v-model="launch.renderMode"><option value="fast">Fast</option><option value="compat">Compat</option></select></label><label><span>WebGL</span><select v-model="launch.webgl"><option :value="true">On</option><option :value="false">Off</option></select></label><label><span>{{ t.cache }}</span><select v-model="launch.cacheMode"><option value="fast">Fast cache</option><option value="safe">Safe</option></select></label><label><span>{{ t.zoom }}</span><select v-model="launch.disableZoom"><option :value="true">Lock</option><option :value="false">Allow</option></select></label></div><button class="btn-secondary" @click="saveLaunch">{{ t.saveLaunch }}</button></section>
<section v-if="status" class="notice">{{ status }}</section>
</div></template><script setup>
import { onMounted, reactive, ref } from 'vue'
const t={title:'AI \u8bbe\u7f6e',desc:'\u79fb\u52a8\u7aef\u4e0e PC \u4e00\u81f4\uff1a\u6e20\u9053\u3001\u6a21\u578b\u3001\u5e76\u53d1\u3001\u9650\u901f\u90fd\u53ef\u914d\u7f6e\u3002',save:'\u4fdd\u5b58',baseUrl:'Base URL',apiKey:'API Key',model:'\u6a21\u578b',models:'\u83b7\u53d6\u6a21\u578b',batch:'\u5355\u6279',threads:'\u5e76\u53d1',interval:'\u95f4\u9694ms',retry:'429\u91cd\u8bd5',target:'\u76ee\u6807\u8bed\u8a00\uff1a\u7b80\u4f53\u4e2d\u6587',testSource:'\u8f93\u5165\u6d4b\u8bd5\u539f\u6587',test:'\u6d4b\u8bd5\u7ffb\u8bd1',launch:'\u6e38\u620f\u6d41\u7545\u5ea6',render:'\u6e32\u67d3',cache:'\u7f13\u5b58',zoom:'\u7f29\u653e',saveLaunch:'\u4fdd\u5b58\u8fd0\u884c\u53c2\u6570'}
const providers=[{value:'openai',label:'OpenAI'},{value:'anthropic',label:'Anthropic'},{value:'ollama',label:'Ollama'}]
const aiForm=reactive({provider:'openai',apiKey:'',baseUrl:'https://api.openai.com/v1',model:'',batchSize:50,concurrency:1,requestIntervalMs:1200,rateLimitRetries:3,targetLang:'\u7b80\u4f53\u4e2d\u6587',availableModels:[]})
const launch=reactive({renderMode:'fast',webgl:true,cacheMode:'fast',disableZoom:true,domStorage:true,fileAccess:true,mediaAutoplay:true})
const busy=reactive({models:false,test:false});const status=ref('');const testSource=ref('Hello, welcome to the game.');const testResult=ref('')
function parse(raw){try{return raw?typeof raw==='string'?JSON.parse(raw):raw:{}}catch(e){return{ok:false,error:e.message}}}
function base(provider){return provider==='anthropic'?'https://api.anthropic.com':provider==='ollama'?'http://127.0.0.1:11434':'https://api.openai.com/v1'}
function payload(){return {...aiForm,availableModels:aiForm.availableModels||[]}}
function selectProvider(p){aiForm.provider=p;aiForm.baseUrl=base(p);if(p==='ollama')aiForm.apiKey=''}
function loadAiSettings(){const res=parse(window.RPGRenPyShell?.androidAiSettings?window.RPGRenPyShell.androidAiSettings():localStorage.getItem('rpgrtl_ai_settings'));const ai=res.ai||res.settings||res;if(ai&&Object.keys(ai).length)Object.assign(aiForm,{...ai,provider:ai.provider||'openai',baseUrl:ai.baseUrl||base(ai.provider),targetLang:ai.targetLang||'\u7b80\u4f53\u4e2d\u6587'});}
function saveAiSettings(){const data=payload();try{const raw=window.RPGRenPyShell?.saveAiSettings?window.RPGRenPyShell.saveAiSettings(JSON.stringify(data)):(localStorage.setItem('rpgrtl_ai_settings',JSON.stringify(data)),JSON.stringify({ok:true}));const res=parse(raw);if(res.ok===false)throw new Error(res.error||'save failed');status.value='AI \u8bbe\u7f6e\u5df2\u4fdd\u5b58'}catch(e){status.value='\u4fdd\u5b58\u5931\u8d25\uff1a'+(e.message||e)}}
function fetchModels(){busy.models=true;try{const raw=window.RPGRenPyShell?.androidAiModels?window.RPGRenPyShell.androidAiModels(JSON.stringify(payload())):JSON.stringify({ok:true,models:[aiForm.model||'gpt-4o-mini']});const res=parse(raw);if(res.ok===false)throw new Error(res.error||'models failed');aiForm.availableModels=res.models||[];if(!aiForm.model)aiForm.model=aiForm.availableModels[0]||'';status.value='\u5df2\u83b7\u53d6 '+aiForm.availableModels.length+' \u4e2a\u6a21\u578b'}catch(e){status.value='\u83b7\u53d6\u5931\u8d25\uff1a'+(e.message||e)}finally{busy.models=false}}
function testAi(){if(!testSource.value.trim())return;busy.test=true;testResult.value='';try{const req={settings:payload(),entries:[{entry_id:'mobile-test',source:testSource.value}],targetLang:aiForm.targetLang};const raw=window.RPGRenPyShell?.androidAiTranslate?window.RPGRenPyShell.androidAiTranslate(JSON.stringify(req)):JSON.stringify({ok:true,translations:[{entry_id:'mobile-test',target:'\u4f60\u597d\uff0c\u6b22\u8fce\u6765\u5230\u6e38\u620f\u3002'}]});const res=parse(raw);if(res.ok===false)throw new Error(res.error||'test failed');const first=Array.isArray(res.translations)?res.translations[0]:null;testResult.value=typeof first==='string'?first:first?.target||'';status.value=testResult.value?'\u6d4b\u8bd5\u6210\u529f':'\u672a\u8fd4\u56de\u8bd1\u6587'}catch(e){status.value='\u6d4b\u8bd5\u5931\u8d25\uff1a'+(e.message||e)}finally{busy.test=false}}
function saveLaunch(){try{window.RPGRenPyShell?.saveLaunchSettings?.(JSON.stringify(launch));status.value='\u8fd0\u884c\u53c2\u6570\u5df2\u4fdd\u5b58\uff0c\u4e0b\u6b21\u542f\u52a8\u751f\u6548'}catch(e){status.value='\u4fdd\u5b58\u5931\u8d25\uff1a'+(e.message||e)}}
onMounted(loadAiSettings)
</script><style scoped>.active{background:linear-gradient(135deg,#4dd6c8,#6da7ff)!important;color:#06111c!important}label span{display:block;color:#8da1bc;font-size:10px;margin-bottom:4px}</style>
