<template><div class="stack">
<section class="card glass-panel header-card"><div class="header-info"><h2 class="card-title">{{ t.title }}</h2><p class="card-desc">{{ t.desc }}</p></div><button class="btn-primary" :disabled="loading" @click="loadTranslations">{{ t.load }}</button></section>
<section class="mobile-grid"><div class="card metric"><span>{{ t.total }}</span><strong>{{ translations.length }}</strong></div><div class="card metric"><span>{{ t.missing }}</span><strong>{{ missingAll }}</strong></div><div class="card metric"><span>{{ t.done }}</span><strong>{{ doneCount }}</strong></div><div class="card metric"><span>{{ t.visible }}</span><strong>{{ filtered.length }}</strong></div></section>
<section class="card glass-panel card-pad stack"><div class="action-grid two"><input v-model="keyword" :placeholder="t.search"/><button class="btn-secondary" @click="missingOnly=!missingOnly">{{ missingOnly?t.showAll:t.onlyMissing }}</button><button class="btn-primary" :disabled="aiBusy||!missingEntries.length" @click="translateMissing"><span v-if="aiBusy" class="mini-spinner"></span>{{ t.ai }}</button><button class="btn-secondary" :disabled="!translations.length" @click="saveTranslations">{{ t.save }}</button></div><div v-if="progress.total" class="notice">{{ progress.message }} ? {{ progress.current }}/{{ progress.total }}</div></section>
<section v-if="status" class="notice">{{ status }}</section>
<section class="list"><article v-for="item in filtered.slice(0,80)" :key="item.entry_id||item.id" class="card item-card"><div class="item-head"><span>{{ item.category||item.file||'text' }}</span><span>{{ item.target?t.translated:t.pending }}</span></div><div class="source-box">{{ item.source||item.original }}</div><textarea v-model="item.target" :placeholder="t.placeholder"></textarea></article></section>
</div></template><script setup>
import { computed, onMounted, reactive, ref } from 'vue'
const t={title:'\u7ffb\u8bd1\u5de5\u4f5c\u53f0',desc:'\u9ad8\u5bc6\u5ea6\u67e5\u770b\u6587\u672c\u3001\u7edf\u8ba1\u8fdb\u5ea6\u5e76\u6279\u91cf\u7ffb\u8bd1\u7a7a\u767d\u9879\u3002',load:'\u8f7d\u5165',total:'\u603b\u6570',missing:'\u672a\u8bd1',done:'\u5df2\u8bd1',visible:'\u5f53\u524d',search:'\u641c\u7d22\u539f\u6587/\u8bd1\u6587/\u6587\u4ef6',onlyMissing:'\u4ec5\u672a\u8bd1',showAll:'\u663e\u793a\u5168\u90e8',ai:'AI \u7ffb\u8bd1\u7a7a\u767d',save:'\u4fdd\u5b58',translated:'\u5df2\u8bd1',pending:'\u5f85\u8bd1',placeholder:'\u5728\u6b64\u8f93\u5165\u8bd1\u6587...'}
const translations=ref([]),loading=ref(false),aiBusy=ref(false),keyword=ref(''),missingOnly=ref(false),status=ref('');const progress=reactive({current:0,total:0,message:''})
const filtered=computed(()=>{const k=keyword.value.toLowerCase();return translations.value.filter(i=>{if(missingOnly.value&&String(i.target||'').trim())return false;if(!k)return true;return [i.source,i.original,i.target,i.file,i.category].some(v=>String(v||'').toLowerCase().includes(k))})})
const missingAll=computed(()=>translations.value.filter(i=>!String(i.target||'').trim()).length);const doneCount=computed(()=>translations.value.length-missingAll.value);const missingEntries=computed(()=>translations.value.filter(i=>!String(i.target||'').trim()).slice(0,30))
function parse(raw){try{return raw?typeof raw==='string'?JSON.parse(raw):raw:{}}catch(e){return{ok:false,error:e.message}}}
function loadTranslations(){loading.value=true;status.value='';try{const res=parse(window.RPGRenPyShell?.androidTranslationEntries?window.RPGRenPyShell.androidTranslationEntries(500):'');if(res.ok===false)throw new Error(res.error||'load failed');translations.value=Array.isArray(res.entries)?res.entries:[];status.value='\u5df2\u8f7d\u5165 '+translations.value.length+' \u6761\u6587\u672c'}catch(e){status.value='\u8f7d\u5165\u5931\u8d25\uff1a'+(e.message||e)}finally{loading.value=false}}
function loadAiSettings(){return parse(window.RPGRenPyShell?.androidAiSettings?window.RPGRenPyShell.androidAiSettings():localStorage.getItem('rpgrtl_ai_settings'))}
function translateMissing(){const targets=missingEntries.value;if(!targets.length)return;aiBusy.value=true;progress.current=0;progress.total=targets.length;progress.message='AI \u6b63\u5728\u7ffb\u8bd1...';try{const settings=loadAiSettings();const req={settings,entries:targets,targetLang:settings.targetLang||'\u7b80\u4f53\u4e2d\u6587'};const raw=window.RPGRenPyShell?.androidAiTranslate?window.RPGRenPyShell.androidAiTranslate(JSON.stringify(req)):JSON.stringify({ok:true,translations:targets.map(i=>({entry_id:i.entry_id,target:'[AI] '+(i.source||i.original)}))});const res=parse(raw);if(res.ok===false)throw new Error(res.error||'AI failed');const arr=Array.isArray(res.translations)?res.translations:[];const byId=new Map(arr.map(x=>[String(x.entry_id||x.id||''),x]));let changed=0;targets.forEach((entry,index)=>{const hit=byId.get(String(entry.entry_id||entry.id||''))||arr[index];const target=typeof hit==='string'?hit:hit?.target;if(target){entry.target=target;changed++}progress.current++});progress.message='AI \u5df2\u751f\u6210 '+changed+' \u6761\u8bd1\u6587';status.value=progress.message}catch(e){status.value='AI \u7ffb\u8bd1\u5931\u8d25\uff1a'+(e.message||e)}finally{aiBusy.value=false}}
function saveTranslations(){try{const entries=translations.value.filter(i=>String(i.target||'').trim());const res=parse(window.RPGRenPyShell?.androidSaveTranslationEntries?window.RPGRenPyShell.androidSaveTranslationEntries(JSON.stringify({entries})):JSON.stringify({ok:true,count:entries.length}));if(res.ok===false)throw new Error(res.error||'save failed');status.value='\u5df2\u4fdd\u5b58 '+(res.count??entries.length)+' \u6761\u8bd1\u6587'}catch(e){status.value='\u4fdd\u5b58\u5931\u8d25\uff1a'+(e.message||e)}}
onMounted(loadTranslations)
</script>
