# Auto-generated by RPGRenPyLocalizer.
# Live text bridge based on projz_renpy_translation's proven hook pattern.
init -7 python:
    import os
    import json
    import re
    import time
    import threading

    try:
        import urllib2
    except Exception:
        import urllib.request as urllib2

    try:
        string_types = (basestring,)
    except NameError:
        string_types = (str,)

    _rpgrtl_live_server = "http://127.0.0.1:32180"
    _rpgrtl_bridge_version = "android-2026-07-26.4"
    _rpgrtl_request_timeout = 0.45
    _rpgrtl_translation_cache = {}
    _rpgrtl_local_cache = {}
    _rpgrtl_pending_seen = []
    _rpgrtl_pending_lookup = set()
    _rpgrtl_translatable_cache = {}  # {text: bool} — avoids regex every frame
    _rpgrtl_last_restart_interaction = 0
    _rpgrtl_restart_interval = 0.12
    _rpgrtl_last_notify_seq = 0
    _rpgrtl_last_force_seq = 0
    _rpgrtl_server_id = ""
    # Faster poll so concurrent AI results hit the screen sooner.
    _rpgrtl_bg_loop_interval = 0.20
    _rpgrtl_tid_what = (None, None)
    _rpgrtl_active_widget = None
    _rpgrtl_active_source = ""
    _rpgrtl_force_text = ""
    _rpgrtl_force_applied = False
    _rpgrtl_debug_file = os.path.join(os.path.dirname(config.gamedir), ".rpgrtl_workspace", "rpgrtl_bridge_debug.log")
    _rpgrtl_local_cache_file = os.path.join(os.path.dirname(config.gamedir), ".rpgrtl_workspace", "renpy_live_translation.json")
    _rpgrtl_skip_mode = False  # True when Ren'Py is in fast-forward/skip mode

    # CJK font setup — ensure Chinese characters render correctly
    try:
        _rpgrtl_cjk_font = None
        for _f in (
            "game/DejaVuSans.ttf",
            "C:/windows/Fonts/msyh.ttc",
            "C:/windows/Fonts/simhei.ttf",
            "C:/Windows/Fonts/msyh.ttc",
            "C:/Windows/Fonts/msyh.ttf",
            "C:/Windows/Fonts/simhei.ttf",
            "C:/Windows/Fonts/simsun.ttc",
            "C:/Windows/Fonts/NotoSansCJK-Regular.ttc",
            "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
            "/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",
            "/System/Library/Fonts/PingFang.ttc",
        ):
            if os.path.exists(_f):
                _rpgrtl_cjk_font = _f
                break
        if _rpgrtl_cjk_font:
            try:
                config.default_font = _rpgrtl_cjk_font
            except Exception:
                pass
            try:
                gui.text_font = _rpgrtl_cjk_font
            except Exception:
                pass
            try:
                gui.name_text_font = _rpgrtl_cjk_font
            except Exception:
                pass
            try:
                gui.interface_text_font = _rpgrtl_cjk_font
            except Exception:
                pass
            for _sname in (
                "default", "say_dialogue", "say_label", "say_thought",
                "input", "input_prompt",
                "choice_button_text", "choice_chosen_button_text",
                "menu_choice", "menu_choice_chosen",
                "menu_choice_button_text", "menu_choice_chosen_button_text",
                "button_text", "small_button_text",
                "navigation_button_text",
                "page_button_text",
                "quick_button_text",
                "slot_button_text",
                "label_text", "prompt_text",
                "textbutton_text",
            ):
                try:
                    getattr(style, _sname).font = _rpgrtl_cjk_font
                except Exception:
                    pass
    except Exception:
        pass

    _rpgrtl_debug_buffer = []
    _rpgrtl_debug_last_flush = 0.0
    def _rpgrtl_debug(msg):
        try:
            _rpgrtl_debug_buffer.append(time.strftime("%Y-%m-%d %H:%M:%S") + " " + msg + "\n")
            now = time.time()
            if len(_rpgrtl_debug_buffer) >= 10 or now - _rpgrtl_debug_last_flush >= 3.0:
                with open(_rpgrtl_debug_file, "a", encoding="utf-8") as f:
                    for line in _rpgrtl_debug_buffer:
                        f.write(line)
                _rpgrtl_debug_buffer[:] = []
                _rpgrtl_debug_last_flush = now
        except Exception:
            pass

    def _rpgrtl_send(endpoint, payload, timeout=None):
        if timeout is None:
            timeout = _rpgrtl_request_timeout
        data = json.dumps(payload).encode("utf-8")
        req = urllib2.Request(_rpgrtl_live_server + endpoint, data, {"Content-Type": "application/json"})
        return json.loads(urllib2.urlopen(req, timeout=timeout).read().decode("utf-8"))

    def _rpgrtl_log(event, payload=None):
        try:
            if payload is None:
                payload = {}
            payload["bridge_version"] = _rpgrtl_bridge_version
            payload["pid"] = os.getpid()
            _rpgrtl_send("/log", {"event": event, "payload": payload}, timeout=0.5)
        except Exception:
            pass

    def _rpgrtl_tagless(text):
        try:
            return re.sub(r"\{[^}]*\}", "", text).strip()
        except Exception:
            return text.strip() if isinstance(text, string_types) else ""

    def _rpgrtl_is_translatable(text):
        if not isinstance(text, string_types):
            return False
        cached = _rpgrtl_translatable_cache.get(text)
        if cached is not None:
            return cached
        clean = _rpgrtl_tagless(text).strip()
        if len(clean) <= 1 or len(clean) > 1200:
            _rpgrtl_translatable_cache[text] = False
            return False
        if clean.startswith("[") and clean.endswith("]"):
            _rpgrtl_translatable_cache[text] = False
            return False
        if sum(1 for ch in clean if ch.isalnum()) < 2:
            _rpgrtl_translatable_cache[text] = False
            return False
        lower = clean.lower()
        if lower.startswith("http://") or lower.startswith("https://"):
            _rpgrtl_translatable_cache[text] = False
            return False
        if lower.endswith((".png", ".jpg", ".jpeg", ".webp", ".rpy", ".rpyc")):
            _rpgrtl_translatable_cache[text] = False
            return False
        for ch in clean:
            if "a" <= ch.lower() <= "z":
                _rpgrtl_translatable_cache[text] = True
                return True
            if "぀" <= ch <= "ヿ":
                _rpgrtl_translatable_cache[text] = True
                return True
        _rpgrtl_translatable_cache[text] = False
        return False

    def _rpgrtl_has_cjk(text):
        """Check if text contains any CJK characters (needs CJK font to render)."""
        if not isinstance(text, string_types):
            return False
        for ch in text:
            if "一" <= ch <= "鿿" or "㐀" <= ch <= "䶿" or "豈" <= ch <= "﫿":
                return True
        return False

    def _rpgrtl_normalize_fullwidth(text):
        """Convert fullwidth (全角) ASCII characters to halfwidth (半角).

        Fullwidth chars U+FF01–U+FF5E map to ASCII U+0021–U+007E (offset -0xFEE0).
        Fullwidth space U+3000 maps to ASCII space U+0020.
        This prevents AI-translated text from using fullwidth braces, parens, quotes etc.
        that would break Ren'Py text tag parsing.
        """
        if not isinstance(text, string_types):
            return text
        out = []
        for ch in text:
            cp = ord(ch)
            if 0xFF01 <= cp <= 0xFF5E:
                out.append(chr(cp - 0xFEE0))
            elif cp == 0x3000:  # ideographic space
                out.append(" ")
            else:
                out.append(ch)
        return "".join(out)

    def _rpgrtl_strip_font_tags(text):
        """Strip any existing {font=...}...{/font} tags, handling both half/fullwidth braces."""
        if not isinstance(text, string_types):
            return text
        # Keep arbitrary fullwidth braces neutralized. Only remove font tags,
        # including spaced, fullwidth, nested, and orphan closing variants.
        return re.sub(r"[\{｛]\s*/?\s*font(?:\s*=\s*[^\}｝]*)?\s*[\}｝]", "", text, flags=re.I).strip()

    def _rpgrtl_wrap_font(text):
        """Wrap text with CJK font tag, stripping any existing/broken font tags first."""
        clean = _rpgrtl_strip_font_tags(text)
        if not _rpgrtl_cjk_font or not clean or not _rpgrtl_has_cjk(clean):
            return clean
        return "{font=" + _rpgrtl_cjk_font + "}" + clean + "{/font}"

    def _rpgrtl_candidates(source):
        result = []
        seen = set()
        for value in (source,):
            if not isinstance(value, string_types):
                continue
            variants = [value, value.strip(), _rpgrtl_tagless(value), re.sub(r"\s+", " ", value.strip())]
            stripped = value.strip()
            if len(stripped) >= 2 and stripped[0] == stripped[-1] and stripped[0] in ('"', "'"):
                variants.append(stripped[1:-1])
            for item in variants:
                if item and item not in seen:
                    seen.add(item)
                    result.append(item)
        return result

    def _rpgrtl_lookup(text):
        if not isinstance(text, string_types) or not text.strip():
            return None
        # Merge both maps so a partial in-memory pull cannot hide local/disk hits.
        if _rpgrtl_translation_cache and _rpgrtl_local_cache:
            translations = dict(_rpgrtl_local_cache)
            translations.update(_rpgrtl_translation_cache)
        else:
            translations = _rpgrtl_translation_cache or _rpgrtl_local_cache
        if not translations:
            return None
        for key in _rpgrtl_candidates(text):
            if key in translations:
                result = translations[key]
                return _rpgrtl_strip_font_tags(result)
        return None

    def _rpgrtl_restart_interaction(reason="refresh"):
        global _rpgrtl_last_restart_interaction
        # Never restart during skip/fast-forward mode — causes dialogue advancement crash
        if _rpgrtl_skip_mode:
            return False
        now = time.time()
        if now - _rpgrtl_last_restart_interaction < _rpgrtl_restart_interval:
            return False
        _rpgrtl_last_restart_interaction = now
        try:
            renpy.restart_interaction()
            return True
        except Exception:
            pass
        return False

    def _rpgrtl_load_local_cache():
        global _rpgrtl_local_cache
        try:
            if os.path.isfile(_rpgrtl_local_cache_file):
                with open(_rpgrtl_local_cache_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                if (hasattr(data, "get") and hasattr(data, "keys")):
                    cached = data.get("translations", {})
                    if (hasattr(cached, "get") and hasattr(cached, "keys")):
                        _rpgrtl_local_cache = {k: _rpgrtl_strip_font_tags(v) for k, v in cached.items()}
                        _rpgrtl_log("local_cache_loaded", {"count": len(cached)})
        except Exception:
            pass

    def _rpgrtl_pull_translations():
        global _rpgrtl_translation_cache
        try:
            payload = _rpgrtl_send("/pull", {"pid": os.getpid()}, timeout=3.0)
            if (hasattr(payload, "get") and hasattr(payload, "keys")):
                translations = payload.get("translations", {})
                if (hasattr(translations, "get") and hasattr(translations, "keys")):
                    translations = {k: _rpgrtl_strip_font_tags(v) for k, v in translations.items()}
                    _rpgrtl_translation_cache = translations
                    _rpgrtl_local_cache.update(translations)
                    _rpgrtl_log("pull_success", {"count": len(translations)})
        except Exception:
            pass

    _rpgrtl_seen_queued = set()  # deduplicate pending_seen

    def _rpgrtl_report_seen(source, displayed, target, kind):
        key = source.strip() if isinstance(source, str) else ""
        if key and key in _rpgrtl_seen_queued:
            return
        if key:
            _rpgrtl_seen_queued.add(key)
        # Limit queue size to prevent memory leak
        if len(_rpgrtl_pending_seen) > 200:
            _rpgrtl_pending_seen[:] = _rpgrtl_pending_seen[-100:]
        _rpgrtl_pending_seen.append({"event": kind, "what": source, "displayed": displayed, "target": target or "", "matched": bool(target)})
        if len(_rpgrtl_seen_queued) > 5000:
            _rpgrtl_seen_queued.clear()

    def _rpgrtl_take_force_text(expected_source=None):
        global _rpgrtl_force_text
        forced = _rpgrtl_force_text
        if not forced:
            return ""
        if expected_source and not _rpgrtl_is_translatable(expected_source):
            return ""
        _rpgrtl_force_text = ""
        return forced

    def _rpgrtl_remember_active_widget(widget, source):
        global _rpgrtl_active_widget, _rpgrtl_active_source
        if widget is not None and source and _rpgrtl_is_translatable(source):
            _rpgrtl_active_widget = widget
            _rpgrtl_active_source = source

    def _rpgrtl_patch_active_widget(reason="translation_ready", forced_text=None):
        widget = _rpgrtl_active_widget
        source = _rpgrtl_active_source
        translated = forced_text if forced_text else _rpgrtl_lookup(source)
        _rpgrtl_debug("patch_active: widget=" + repr(type(widget).__name__ if widget else None) + " source=" + repr((source or "")[:40]) + " translated=" + repr((translated or "")[:40]) + " reason=" + reason)
        if not widget and not translated:
            return False
        if not translated:
            return False
        patched = False
        if widget is not None:
            try:
                if _rpgrtl_old_set_text:
                    _rpgrtl_old_set_text(widget, translated, None, False, True)
                else:
                    widget.text = [translated]
                _rpgrtl_text_modified[id(widget)] = translated
                if source:
                    _rpgrtl_text_source[id(widget)] = source
                _rpgrtl_log("active_widget_patched", {"source": (source or "")[:180], "target": translated[:180], "reason": reason})
                _rpgrtl_debug("patch_active SUCCESS: target=" + repr(translated[:60]))
                patched = True
            except Exception as exc:
                _rpgrtl_log("active_widget_patch_failed", {"source": (source or "")[:180], "error": str(exc), "reason": reason})
                _rpgrtl_debug("patch_active FAILED: " + repr(exc))
        try:
            for w in renpy.display.screen.current_screen().children if hasattr(renpy.display.screen, "current_screen") and callable(renpy.display.screen.current_screen) else []:
                if hasattr(w, "text"):
                    if _rpgrtl_old_set_text:
                        _rpgrtl_old_set_text(w, translated, None, False, True)
                    else:
                        w.text = [translated]
                    _rpgrtl_text_modified[id(w)] = translated
                    if source:
                        _rpgrtl_text_source[id(w)] = source
                    patched = True
        except Exception:
            pass
        if patched:
            try:
                _rpgrtl_restart_interaction(reason)
            except Exception:
                pass
        return patched

    # Direct widget update: find Text widget with id="what" via screen API
    # and call set_text() on it. Does NOT restart interaction.
    def _rpgrtl_force_update_current_text(forced_text):
        _rpgrtl_debug("force_update_current_text: " + repr(forced_text[:60]))
        updated = False
        try:
            # Try renpy.display.screen.get_screen("say") to get the say screen
            say_screen = None
            try:
                say_screen = renpy.display.screen.get_screen("say")
            except Exception:
                pass
            if say_screen is None:
                # Fallback: try current_screen
                try:
                    if hasattr(renpy.display.screen, "current_screen") and callable(renpy.display.screen.current_screen):
                        say_screen = renpy.display.screen.current_screen()
                except Exception:
                    pass
            if say_screen is not None:
                # Find the "what" widget by traversing children
                def find_what_widget(obj, depth=0):
                    if depth > 20:
                        return None
                    # Check if this object has the id "what"
                    if hasattr(obj, "widget_id") and obj.widget_id == "what":
                        return obj
                    if hasattr(obj, "id") and obj.id == "what" and hasattr(obj, "text"):
                        return obj
                    # Check children
                    if hasattr(obj, "children"):
                        for child in obj.children:
                            result = find_what_widget(child, depth + 1)
                            if result:
                                return result
                    if hasattr(obj, "child"):
                        result = find_what_widget(obj.child, depth + 1)
                        if result:
                            return result
                    if hasattr(obj, "content"):
                        result = find_what_widget(obj.content, depth + 1)
                        if result:
                            return result
                    return None
                widget = find_what_widget(say_screen)
                if widget is not None:
                    _rpgrtl_debug("force_update: found widget " + repr(type(widget).__name__))
                    if _rpgrtl_old_set_text:
                        _rpgrtl_old_set_text(widget, forced_text, None, False, True)
                    else:
                        widget.text = [forced_text]
                    _rpgrtl_text_modified[id(widget)] = forced_text
                    if _rpgrtl_active_source:
                        _rpgrtl_text_source[id(widget)] = _rpgrtl_active_source
                    _rpgrtl_debug("force_update: set_text done")
                    updated = True
                    try:
                        import pygame
                        pygame.event.post(pygame.event.Event(25))
                    except Exception:
                        pass
                else:
                    _rpgrtl_debug("force_update: 'what' widget not found in screen tree")
            else:
                _rpgrtl_debug("force_update: no screen found")
        except Exception as exc:
            _rpgrtl_debug("force_update EXCEPTION: " + repr(exc))
        return updated

    # Force-update choice buttons on the "choice" screen when translations arrive late.
    # With the Text.render hook now active, this is mostly a backup mechanism.
    def _rpgrtl_force_update_choice_buttons():
        """Patch choice screen buttons with translated text if available."""
        try:
            choice_screen = renpy.display.screen.get_screen("choice")
            if choice_screen is None:
                return False

            def find_all_text_widgets(obj, depth=0):
                """Find all Text widgets in the screen tree."""
                if depth > 30:
                    return []
                results = []
                cls_name = type(obj).__name__
                if hasattr(obj, "text") and isinstance(obj.text, list) and cls_name == "Text":
                    results.append(obj)
                if hasattr(obj, "children"):
                    for child in obj.children:
                        results.extend(find_all_text_widgets(child, depth + 1))
                if hasattr(obj, "child"):
                    results.extend(find_all_text_widgets(obj.child, depth + 1))
                if hasattr(obj, "content"):
                    results.extend(find_all_text_widgets(obj.content, depth + 1))
                return results

            widgets = find_all_text_widgets(choice_screen)
            updated = False
            for widget in widgets:
                current_text = widget.text
                if isinstance(current_text, list) and len(current_text) == 1:
                    txt = current_text[0]
                    if isinstance(txt, str) and txt.strip():
                        translated = _rpgrtl_lookup(txt)
                        if translated and translated != txt:
                            translated = _rpgrtl_wrap_font(translated)
                            widget.text = [translated]
                            _rpgrtl_text_modified[id(widget)] = translated
                            _rpgrtl_text_source[id(widget)] = txt
                            updated = True
                            _rpgrtl_debug("choice_widget_patched: " + repr(txt[:40]) + " -> " + repr(translated[:40]))
            if updated:
                import pygame
                pygame.event.post(pygame.event.Event(25))  # PERIODIC event
            return updated
        except Exception as exc:
            _rpgrtl_debug("force_update_choice EXCEPTION: " + repr(exc))
            return False

    # Track whether a menu is currently active for live patching
    _rpgrtl_menu_active = [False]

    # Hook: Text.set_text (projz pattern - call old first, then self.text=[translated])
    _rpgrtl_old_set_text = None
    try:
        _rpgrtl_old_set_text = renpy.text.text.Text.set_text
    except Exception:
        pass

    def _rpgrtl_hook_set_text(self, text, scope=None, substitute=False, update=True):
        global _rpgrtl_active_widget, _rpgrtl_active_source, _rpgrtl_force_text
        res = _rpgrtl_old_set_text(self, text, scope, substitute, update) if _rpgrtl_old_set_text else None
        if not isinstance(text, (string_types, list)):
            return res
        old_text = None
        if isinstance(text, string_types):
            old_text = text
        elif len(text) == 1 and isinstance(text[0], string_types):
            old_text = text[0]
        if old_text and _rpgrtl_is_translatable(old_text):
            _rpgrtl_remember_active_widget(self, old_text)
            _rpgrtl_debug("set_text TRACK: widget=" + repr(type(self).__name__) + " text=" + repr(old_text[:60]))
        forced = _rpgrtl_force_text if isinstance(_rpgrtl_force_text, string_types) else ""
        if forced and old_text and _rpgrtl_is_translatable(old_text) and not _rpgrtl_skip_mode:
            _rpgrtl_debug("set_text FORCE: old_text=" + repr(old_text[:60]) + " forced=" + repr(forced[:60]))
            try:
                self.text = [forced]
                _rpgrtl_text_modified[id(self)] = forced
                _rpgrtl_text_source[id(self)] = old_text
                _rpgrtl_force_text = ""
                _rpgrtl_log("set_text_force_replace", {"source": old_text[:180], "target": forced[:180]})
                _rpgrtl_patch_active_widget("set_text_force")
                return True
            except Exception as exc:
                _rpgrtl_debug("set_text FORCE FAILED: " + repr(exc))
                _rpgrtl_log("set_text_force_failed", {"source": old_text[:180], "error": str(exc), "target": forced[:180]})
        if not old_text or not _rpgrtl_is_translatable(old_text):
            return res
        translated = _rpgrtl_lookup(old_text)
        if translated and translated != old_text:
            try:
                self.text = [translated]
                _rpgrtl_text_modified[id(self)] = translated
                _rpgrtl_text_source[id(self)] = old_text
                _rpgrtl_log("set_text_replace", {"source": old_text[:180], "target": translated[:180]})
                return True
            except Exception:
                pass
        return res

    # Hook: ADVCharacter.__call__ (track raw what for translate_identifier)
    _rpgrtl_old_character_call = None
    try:
        _rpgrtl_old_character_call = renpy.character.ADVCharacter.__call__
    except Exception:
        pass

    def _rpgrtl_hook_character_call(self, what, **kwargs):
        global _rpgrtl_tid_what
        try:
            _rpgrtl_tid_what = (renpy.game.context().translate_identifier, what)
        except Exception:
            _rpgrtl_tid_what = (None, what)
        return _rpgrtl_old_character_call(self, what, **kwargs)

    # Hook: ADVCharacter.prefix_suffix (projz pattern - return translated directly)
    _rpgrtl_old_prefix_suffix = None
    try:
        _rpgrtl_old_prefix_suffix = renpy.character.ADVCharacter.prefix_suffix
    except Exception:
        pass

    def _rpgrtl_hook_prefix_suffix(self, thing, prefix, body, suffix):
        global _rpgrtl_force_text, _rpgrtl_force_applied
        if _rpgrtl_old_prefix_suffix:
            res = _rpgrtl_old_prefix_suffix(self, thing, prefix, body, suffix)
        else:
            res = (prefix or "") + (body or "") + (suffix or "")
        if body is None or thing not in ("what", "who"):
            return res
        forced = _rpgrtl_force_text if isinstance(_rpgrtl_force_text, string_types) else ""
        if forced and thing == "what" and not _rpgrtl_skip_mode:
            _rpgrtl_debug("prefix_suffix FORCE: body=" + repr(body[:60]) + " forced=" + repr(forced[:60]))
            # Do NOT clear _rpgrtl_force_text here — let do_display handle it.
            # do_display will display the forced text and wait for player input.
            _rpgrtl_force_applied = True
            _rpgrtl_report_seen(body, res, forced, "force_text")
            _rpgrtl_log("prefix_suffix_force_replace", {"source": body[:180], "target": forced[:180]})
            return (prefix or "") + forced + (suffix or "")
        if not _rpgrtl_is_translatable(res):
            return res
        translated = _rpgrtl_lookup(body)
        if translated and translated != body:
            translated = _rpgrtl_wrap_font(translated)
            _rpgrtl_report_seen(body, res, translated, "prefix_suffix")
            try:
                result = _rpgrtl_old_prefix_suffix(self, thing, prefix, translated, suffix) if _rpgrtl_old_prefix_suffix else (prefix or "") + translated + (suffix or "")
                _rpgrtl_log("prefix_suffix_replace", {"source": body[:180], "target": translated[:180]})
                return result
            except Exception:
                return (prefix or "") + translated + (suffix or "")
        _rpgrtl_report_seen(body, res, "", "prefix_suffix")
        if not _rpgrtl_skip_mode:
            _rpgrtl_pending_lookup.add(body.strip())
        return res

    # Hook: ADVCharacter.do_display (projz pattern - replace who/what, handle DTT)
    _rpgrtl_old_do_display = None
    try:
        _rpgrtl_old_do_display = renpy.character.ADVCharacter.do_display
    except Exception:
        pass

    _rpgrtl_dialogue_text_tags = None
    try:
        _rpgrtl_dialogue_text_tags = renpy.character.DialogueTextTags
    except Exception:
        pass

    def _rpgrtl_hook_do_display(self, who, what, **display_args):
        global _rpgrtl_force_text, _rpgrtl_force_applied
        # Check force_text FIRST — this is the primary injection mechanism.
        # Skip during fast-forward mode to avoid race conditions.
        forced = _rpgrtl_force_text if isinstance(_rpgrtl_force_text, string_types) else ""
        if forced and not _rpgrtl_skip_mode:
            forced = _rpgrtl_wrap_font(forced)
            _rpgrtl_debug("do_display FORCE: forced=" + repr(forced[:60]) + " what=" + repr(what[:60]))
            _rpgrtl_force_text = ""
            _rpgrtl_force_applied = False
            _rpgrtl_report_seen(what, what, forced, "force_text")
            _rpgrtl_log("do_display_force_replace", {"source": what[:180], "target": forced[:180]})
            _rpgrtl_old_do_display(self, who, forced, **display_args)
            return
        if _rpgrtl_force_applied:
            _rpgrtl_force_applied = False
            try:
                _rpgrtl_old_do_display(self, who, what, **display_args)
            except Exception:
                pass
            return
        new_what = what
        try:
            context_tid = renpy.game.context().translate_identifier
        except Exception:
            context_tid = None
        tid, raw_what = _rpgrtl_tid_what
        source_what = raw_what if tid == context_tid and isinstance(raw_what, string_types) else what
        forced = _rpgrtl_force_text if isinstance(_rpgrtl_force_text, string_types) else ""
        if forced and source_what and not _rpgrtl_skip_mode:
            _rpgrtl_debug("do_display FORCE: source=" + repr(source_what[:60]) + " forced=" + repr(forced[:60]))
            new_what = forced
            _rpgrtl_force_text = ""
            translated = forced
            _rpgrtl_report_seen(source_what, what, translated, "force_text")
            _rpgrtl_log("do_display_force_replace", {"source": source_what[:180], "target": translated[:180]})
            try:
                _rpgrtl_old_do_display(self, who, forced, **display_args)
            except Exception:
                pass
            return
        else:
            translated = _rpgrtl_lookup(source_what)
            if not translated and source_what != what:
                translated = _rpgrtl_lookup(what)
            if translated:
                new_what = translated
                _rpgrtl_report_seen(source_what, what, translated, "do_display")
                _rpgrtl_log("do_display_replace", {"source": source_what[:180], "target": translated[:180]})
            else:
                _rpgrtl_report_seen(source_what, what, "", "do_display")
                if not _rpgrtl_skip_mode:
                    _rpgrtl_pending_lookup.add(source_what.strip())
        new_who = who
        if isinstance(who, string_types):
            who_translated = _rpgrtl_lookup(who)
            if who_translated:
                new_who = who_translated
        old_dtt = display_args.get("dtt", None)
        new_dtt = None
        if translated and _rpgrtl_dialogue_text_tags and old_dtt is not None:
            try:
                new_dtt = _rpgrtl_dialogue_text_tags(new_what)
                display_args["dtt"] = new_dtt
            except Exception:
                new_dtt = None
        _rpgrtl_old_do_display(self, new_who, new_what, **display_args)
        if new_dtt is not None and old_dtt is not None:
            try:
                for k, v in vars(new_dtt).items():
                    setattr(old_dtt, k, v)
                display_args["dtt"] = old_dtt
            except Exception:
                pass

    # Hook: Menu.execute — translate menu choice labels before display
    _rpgrtl_old_Menu_execute = None
    try:
        _rpgrtl_old_Menu_execute = renpy.ast.Menu.execute
    except Exception:
        pass

    def _rpgrtl_hook_Menu_execute(self):
        # Translate choice labels in-place before the menu is displayed
        try:
            items = getattr(self, 'items', None)
            if items and isinstance(items, list):
                changed = False
                for i, item in enumerate(items):
                    if isinstance(item, (list, tuple)) and len(item) >= 1:
                        label = item[0]
                        if isinstance(label, str) and label.strip():
                            # Do not alter Menu.items: the AST can be reused on
                            # future visits and then leaks translated labels into
                            # the wrong choice. The display filter below injects
                            # cached text at render time instead.
                            _rpgrtl_pending_lookup.add(label.strip())
        except Exception as exc:
            _rpgrtl_debug("menu_choice translate error: " + repr(exc))
        if _rpgrtl_old_Menu_execute:
            _rpgrtl_menu_active[0] = True
            try:
                return _rpgrtl_old_Menu_execute(self)
            finally:
                _rpgrtl_menu_active[0] = False

    # Hook: renpy.display_menu — translate choice labels right before screen display
    _rpgrtl_old_display_menu = None
    try:
        _rpgrtl_old_display_menu = renpy.display_menu
    except Exception:
        pass

    def _rpgrtl_hook_display_menu(items, *args, **kwargs):
        # Preserve the original menu model. Text.render and the menu filter
        # apply the translation only to the visible widget.
        if _rpgrtl_old_display_menu:
            return _rpgrtl_old_display_menu(items, *args, **kwargs)

    # Install hooks
    try:
        if _rpgrtl_old_character_call:
            renpy.character.ADVCharacter.__call__ = _rpgrtl_hook_character_call
    except Exception as e:
        print("[RPGRenPyLocalizer] Hook character_call failed:", e)
    try:
        if _rpgrtl_old_prefix_suffix:
            renpy.character.ADVCharacter.prefix_suffix = _rpgrtl_hook_prefix_suffix
    except Exception as e:
        print("[RPGRenPyLocalizer] Hook prefix_suffix failed:", e)
    try:
        if _rpgrtl_old_do_display:
            renpy.character.ADVCharacter.do_display = _rpgrtl_hook_do_display
    except Exception as e:
        print("[RPGRenPyLocalizer] Hook do_display failed:", e)
    try:
        if _rpgrtl_old_set_text:
            renpy.text.text.Text.set_text = _rpgrtl_hook_set_text
    except Exception as e:
        print("[RPGRenPyLocalizer] Hook Text.set_text failed:", e)
    try:
        if _rpgrtl_old_Menu_execute:
            renpy.ast.Menu.execute = _rpgrtl_hook_Menu_execute
    except Exception as e:
        print("[RPGRenPyLocalizer] Hook Menu.execute failed:", e)
    try:
        if _rpgrtl_old_display_menu:
            renpy.display_menu = _rpgrtl_hook_display_menu
    except Exception as e:
        print("[RPGRenPyLocalizer] Hook display_menu failed:", e)

    # Startup verification: log which hooks were installed
    _rpgrtl_debug("HOOK STATUS: character_call=" + str(_rpgrtl_old_character_call is not None) +
                  " prefix_suffix=" + str(_rpgrtl_old_prefix_suffix is not None) +
                  " do_display=" + str(_rpgrtl_old_do_display is not None) +
                  " set_text=" + str(_rpgrtl_old_set_text is not None) +
                  " Menu.execute=" + str(_rpgrtl_old_Menu_execute is not None) +
                  " display_menu=" + str(_rpgrtl_old_display_menu is not None))
    _rpgrtl_debug("CJK FONT: " + repr(_rpgrtl_cjk_font) + " cache_count=" + str(len(_rpgrtl_local_cache)) + " trans_cache=" + str(len(_rpgrtl_translation_cache)))
    try:
        _def_font = getattr(config, 'default_font', None)
        _gui_font = getattr(gui, 'text_font', None) if 'gui' in dir() else None
        _rpgrtl_debug("FONTS: config.default_font=" + repr(_def_font) + " gui.text_font=" + repr(_gui_font))
    except Exception:
        pass

    # config.say_menu_text_filter: translate menu labels during Menu.execute
    _rpgrtl_prev_menu_filter = getattr(config, "say_menu_text_filter", None)
    def _rpgrtl_menu_text_filter(label):
        if _rpgrtl_prev_menu_filter:
            label = _rpgrtl_prev_menu_filter(label)
        if isinstance(label, str) and label.strip():
            _rpgrtl_debug("menu_filter: " + repr(label[:60]))
            translated = _rpgrtl_lookup(label)
            if translated and translated != label:
                translated = _rpgrtl_wrap_font(translated)
                _rpgrtl_debug("menu_filter REPLACE: " + repr(label[:40]) + " -> " + repr(translated[:40]))
                _rpgrtl_log("menu_filter_replace", {"source": label[:180], "target": translated[:180]})
                return translated
        return label
    config.say_menu_text_filter = _rpgrtl_menu_text_filter

    # config.replace_text: intercept ALL text at render time
    _rpgrtl_config_prev_replace = getattr(config, "replace_text", None)
    def _rpgrtl_config_replace_text(s):
        if not isinstance(s, string_types):
            return s
        if _rpgrtl_config_prev_replace is not None:
            return _rpgrtl_config_prev_replace(s)
        return s
    config.replace_text = _rpgrtl_config_replace_text

    # Text.render() hook: intercept ALL text at render time and apply cached translations.
    # This is the primary injection mechanism — works for dialogue AND choice buttons.
    # self.text is a LIST in Ren'Py, not a string.
    _rpgrtl_text_modified = {}  # {id(widget): translated_text} — tracks widgets we've modified
    _rpgrtl_text_source = {}  # {id(widget): original_source_text} — keeps cache lookup stable after live patching
    _rpgrtl_force_apply_count = 0
    _rpgrtl_render_apply_count = 0
    _rpgrtl_render_diag_until = time.time() + 30  # log all text for first 30 seconds
    _rpgrtl_render_diag_count = 0
    try:
        _rpgrtl_Text_cls = renpy.text.text.Text
        _rpgrtl_orig_Text_render = _rpgrtl_Text_cls.render
        def _rpgrtl_hook_Text_render(self, width, height, st, at):
            global _rpgrtl_force_text, _rpgrtl_force_apply_count, _rpgrtl_render_apply_count
            global _rpgrtl_active_widget, _rpgrtl_active_source, _rpgrtl_render_diag_count
            forced = _rpgrtl_force_text
            wid = id(self)
            # --- Force text injection (manual "hello" test) — skip during fast-forward ---
            if forced and isinstance(forced, string_types) and not _rpgrtl_skip_mode:
                if wid not in _rpgrtl_text_modified:
                    _rpgrtl_force_apply_count += 1
                    _rpgrtl_debug("Text.render FORCE apply: " + repr(forced[:60]) + " count=" + str(_rpgrtl_force_apply_count))
                _rpgrtl_text_modified[wid] = forced
                self.text = [forced]
                result = _rpgrtl_orig_Text_render(self, width, height, st, at + 0.001)
                if _rpgrtl_force_apply_count >= 1:
                    _rpgrtl_force_text = ""
                    _rpgrtl_force_apply_count = 0
                return result
            # --- Diagnostic: log ALL translatable text for first 30 seconds ---
            if time.time() < _rpgrtl_render_diag_until:
                try:
                    _ctl = self.text
                    if isinstance(_ctl, list) and len(_ctl) >= 1 and isinstance(_ctl[0], string_types) and _ctl[0].strip():
                        _raw = _ctl[0]
                        if _rpgrtl_is_translatable(_raw):
                            _rpgrtl_render_diag_count += 1
                            if _rpgrtl_render_diag_count <= 50:
                                _sty = ""
                                try:
                                    _sty = getattr(self, 'style', None)
                                    _sty = getattr(_sty, 'name', '') if _sty else ''
                                except Exception:
                                    pass
                                _rpgrtl_debug("render_diag: style=" + repr(_sty) + " text=" + repr(_raw[:80]))
                except Exception:
                    pass
            # --- Cached translation injection (primary mechanism) ---
            try:
                current_text_list = self.text
                if isinstance(current_text_list, list) and len(current_text_list) >= 1:
                    raw = current_text_list[0]
                    if isinstance(raw, string_types) and raw.strip() and _rpgrtl_is_translatable(raw):
                        # If already translated (self.text was set to translated), skip
                        prev_translated = _rpgrtl_text_modified.get(wid)
                        if prev_translated and isinstance(prev_translated, string_types) and raw == prev_translated:
                            # Already translated — keep tracking the original source, not the Chinese text.
                            # Otherwise notify/cache refresh cannot match the active line until next launch.
                            _rpgrtl_active_widget = self
                            _rpgrtl_active_source = _rpgrtl_text_source.get(wid, raw)
                            return _rpgrtl_orig_Text_render(self, width, height, st, at)
                        # New or changed text — clear stale tracking
                        if prev_translated is not None and prev_translated != raw:
                            _rpgrtl_text_modified.pop(wid, None)
                            _rpgrtl_text_source.pop(wid, None)
                        # Remember this widget for live patching
                        _rpgrtl_active_widget = self
                        _rpgrtl_active_source = raw
                        # Queue for translation if not cached (skip during fast-forward to avoid overload)
                        if raw not in _rpgrtl_translation_cache and not _rpgrtl_skip_mode:
                            _rpgrtl_pending_lookup.add(raw.strip())
                        translated = _rpgrtl_lookup(raw)
                        if translated and translated != raw:
                            translated = _rpgrtl_wrap_font(translated)
                            _rpgrtl_text_modified[wid] = translated
                            _rpgrtl_text_source[wid] = raw
                            self.text = [translated]
                            _rpgrtl_render_apply_count += 1
                            if _rpgrtl_render_apply_count <= 10:
                                _rpgrtl_debug("Text.render CACHE apply: " + repr(raw[:50]) + " -> " + repr(translated[:50]))
                            result = _rpgrtl_orig_Text_render(self, width, height, st, at + 0.001)
                            return result
                        # Text has CJK chars (already translated by menu_filter etc) but
                        # no cache hit — apply {font} tag so CJK glyphs render correctly
                        font_text = _rpgrtl_wrap_font(raw)
                        if font_text != raw:
                            _rpgrtl_text_modified[wid] = font_text
                            _rpgrtl_text_source[wid] = raw
                            self.text = [font_text]
                            result = _rpgrtl_orig_Text_render(self, width, height, st, at + 0.001)
                            return result
            except Exception:
                pass
            return _rpgrtl_orig_Text_render(self, width, height, st, at)
        _rpgrtl_Text_cls.render = _rpgrtl_hook_Text_render
        _rpgrtl_debug("Hooked Text.render")
    except Exception as e:
        print("[RPGRenPyLocalizer] Hook Text.render failed:", e)

    # Load cache + pull from server
    _rpgrtl_load_local_cache()
    try:
        _rpgrtl_pull_translations()
    except Exception:
        pass

    # AST lookahead: extract upcoming dialogue/choices for pre-translation
    _rpgrtl_last_lookahead_node = [None]
    _rpgrtl_lookahead_interval = 1.0
    def _rpgrtl_lookahead_texts():
        """Traverse upcoming AST nodes to extract dialogue and choice texts."""
        try:
            ctx = renpy.game.context()
            current_name = ctx.current
            # Only re-scan if we moved to a new node
            if current_name == _rpgrtl_last_lookahead_node[0]:
                return []
            _rpgrtl_last_lookahead_node[0] = current_name
            current = renpy.game.script.lookup(current_name)
            if current is None:
                return []
        except Exception:
            return []
        results = []
        visited = set()
        queue = []
        # Start from the NEXT node (not current, which is already displayed)
        if current.next:
            queue.append(current.next)
        while queue and len(results) < 300:
            node = queue.pop(0)
            if node is None:
                continue
            nid = id(node)
            if nid in visited:
                continue
            visited.add(nid)
            try:
                if hasattr(node, 'what') and hasattr(node, 'who'):
                    # Say node — extract dialogue text
                    what = getattr(node, 'what', None)
                    if isinstance(what, str) and what.strip():
                        results.append(what)
                elif hasattr(node, 'items') and hasattr(node, 'has_caption'):
                    # Menu node — extract choice labels
                    items = getattr(node, 'items', [])
                    for item in items:
                        if isinstance(item, (list, tuple)) and len(item) >= 1:
                            label = item[0]
                            if isinstance(label, str) and label.strip():
                                results.append(label)
                # Traverse linear next
                nxt = getattr(node, 'next', None)
                if nxt is not None and id(nxt) not in visited:
                    queue.append(nxt)
                # Explore If branches
                entries = getattr(node, 'entries', None)
                if entries and isinstance(entries, list):
                    for entry in entries:
                        if isinstance(entry, (list, tuple)) and len(entry) >= 2:
                            block = entry[1]
                            if isinstance(block, list) and block:
                                queue.append(block[0])
                # Explore Menu choice branches
                items = getattr(node, 'items', None)
                if items and isinstance(items, list) and hasattr(node, 'has_caption'):
                    for item in items:
                        if isinstance(item, (list, tuple)) and len(item) >= 3:
                            block = item[2]
                            if isinstance(block, list) and block:
                                queue.append(block[0])
            except Exception:
                continue
        return results

    # Background thread: poll for new translations
    def _rpgrtl_background_update():
        _rpgrtl_last_lookahead_time = [0.0]
        def _update_loop():
            global _rpgrtl_last_notify_seq, _rpgrtl_last_force_seq, _rpgrtl_server_id, _rpgrtl_active_widget, _rpgrtl_active_source, _rpgrtl_force_text, _rpgrtl_skip_mode
            _rpgrtl_was_skip = False
            while True:
                try:
                    time.sleep(_rpgrtl_bg_loop_interval)
                    now = time.time()
                    # Detect Ren'Py skip/fast-forward mode to prevent crash
                    try:
                        _rpgrtl_skip_mode = bool(getattr(renpy.config, 'skipping', None))
                    except Exception:
                        _rpgrtl_skip_mode = False
                    # When skip mode ends, do a single refresh to show translations
                    if _rpgrtl_was_skip and not _rpgrtl_skip_mode:
                        _rpgrtl_was_skip = False
                        _rpgrtl_restart_interaction("skip_ended")
                    if _rpgrtl_skip_mode:
                        _rpgrtl_was_skip = True
                    # AST lookahead: every 5 seconds, send upcoming texts for pre-translation
                    if now - _rpgrtl_last_lookahead_time[0] >= _rpgrtl_lookahead_interval:
                        _rpgrtl_last_lookahead_time[0] = now
                        try:
                            upcoming = _rpgrtl_lookahead_texts()
                            if upcoming:
                                # Filter out already-translated texts
                                to_send = [t for t in upcoming if t not in _rpgrtl_translation_cache and t not in _rpgrtl_local_cache]
                                if to_send:
                                    payload = _rpgrtl_send("/pre_translate", {"texts": to_send[:300]}, timeout=1.5)
                                    if hasattr(payload, "get") and hasattr(payload, "keys"):
                                        trans = payload.get("translations", {})
                                        if hasattr(trans, "items"):
                                            for src, tgt in trans.items():
                                                if src and tgt:
                                                    _rpgrtl_translation_cache[src] = tgt
                                                    _rpgrtl_local_cache[src] = tgt
                                    _rpgrtl_debug("lookahead: " + str(len(upcoming)) + " upcoming, " + str(min(len(to_send), 300)) + " sent")
                                    _rpgrtl_log("lookahead", {"upcoming": len(upcoming), "sent": min(len(to_send), 300)})
                        except Exception as _la_exc:
                            _rpgrtl_debug("lookahead EXCEPTION: " + repr(_la_exc))
                    new_translations = {}
                    # Batch /seen: send all pending seen events in ONE HTTP call
                    batch = []
                    while _rpgrtl_pending_seen:
                        try:
                            batch.append(_rpgrtl_pending_seen.pop(0))
                        except IndexError:
                            break
                    if batch:
                        try:
                            payload = _rpgrtl_send("/seen_batch", {"items": batch[:100]}, timeout=1.0)
                            if hasattr(payload, "get") and hasattr(payload, "keys"):
                                targets = payload.get("targets", [])
                                for i, event in enumerate(batch[:100]):
                                    if i < len(targets):
                                        target = str(targets[i] or "")
                                        source = str(event.get("what", "") or "")
                                        if target and source:
                                            _rpgrtl_translation_cache[source] = target
                                            _rpgrtl_local_cache[source] = target
                                            new_translations[source] = target
                        except Exception:
                            for event in batch:
                                _rpgrtl_pending_seen.append(event)
                    # Batch /translation: send pending lookups (cap per tick, requeue misses)
                    all_lookups = list(_rpgrtl_pending_lookup)
                    lookups = all_lookups[:100]
                    _rpgrtl_pending_lookup.clear()
                    for text in all_lookups[100:]:
                        _rpgrtl_pending_lookup.add(text)
                    if lookups:
                        try:
                            payload = _rpgrtl_send("/translation_batch", {"texts": lookups}, timeout=1.5)
                            if hasattr(payload, "get") and hasattr(payload, "keys"):
                                trans = payload.get("translations", {})
                                if hasattr(trans, "items"):
                                    for src, tgt in trans.items():
                                        if src and tgt:
                                            _rpgrtl_translation_cache[src] = tgt
                                            _rpgrtl_local_cache[src] = tgt
                                            new_translations[src] = tgt
                        except Exception:
                            pass
                        # Re-add texts that still lack a translation (host owns AI queue/cooldown)
                        for text in lookups:
                            if text not in _rpgrtl_translation_cache and text not in _rpgrtl_local_cache:
                                _rpgrtl_pending_lookup.add(text)
                    # Proactively request translation for current active source
                    active_src = _rpgrtl_active_source
                    if active_src and active_src.strip() and active_src not in _rpgrtl_translation_cache and active_src not in _rpgrtl_local_cache and not _rpgrtl_skip_mode:
                        _rpgrtl_pending_lookup.add(active_src.strip())
                    # Patch active widget if translation just arrived
                    # Skip during fast-forward mode to avoid race conditions
                    if not _rpgrtl_skip_mode and active_src and _rpgrtl_is_translatable(active_src):
                        translated = _rpgrtl_lookup(active_src)
                        if translated and translated != active_src:
                            _rpgrtl_debug("active_src has translation: " + repr(active_src[:40]) + " -> " + repr(translated[:40]))
                            _rpgrtl_force_update_current_text(translated)
                    # If new translations arrived and a menu is active, patch choice buttons
                    # Skip during fast-forward to avoid race conditions
                    if not _rpgrtl_skip_mode and new_translations and _rpgrtl_menu_active[0]:
                        try:
                            _rpgrtl_force_update_choice_buttons()
                        except Exception:
                            pass
                    try:
                        notify_payload = _rpgrtl_send("/notify", {"pid": os.getpid()}, timeout=0.45)
                        if hasattr(notify_payload, "get") and hasattr(notify_payload, "keys"):
                            server_seq = int(notify_payload.get("seq", 0))
                            server_id = str(notify_payload.get("server_id", "") or "")
                            translation_count = int(notify_payload.get("translation_count", 0) or 0)
                            force_text = str(notify_payload.get("force_text", "") or "")
                            force_source = str(notify_payload.get("force_source", "") or "")
                            force_seq = int(notify_payload.get("force_seq", 0) or 0)
                            inline_trans = notify_payload.get("translations", {})
                            _rpgrtl_debug("notify parsed: seq=" + str(server_seq) + " force_text=" + repr(force_text[:60]) + " last_seq=" + str(_rpgrtl_last_notify_seq))
                            server_changed = bool(server_id and server_id != _rpgrtl_server_id)
                            cache_changed = translation_count != len(_rpgrtl_translation_cache)
                            got_new_map = False
                            if server_changed or server_seq != _rpgrtl_last_notify_seq or cache_changed:
                                _rpgrtl_server_id = server_id
                                _rpgrtl_last_notify_seq = server_seq
                                # Prefer inline map from notify to avoid an extra /pull under Wine latency
                                if hasattr(inline_trans, "items") and len(inline_trans) > 0:
                                    for src, tgt in inline_trans.items():
                                        if src and tgt:
                                            clean = _rpgrtl_strip_font_tags(tgt)
                                            _rpgrtl_translation_cache[src] = clean
                                            _rpgrtl_local_cache[src] = clean
                                            new_translations[src] = clean
                                    got_new_map = True
                                else:
                                    _rpgrtl_pull_translations()
                                    got_new_map = True
                            # Always re-check active line against (possibly updated) cache
                            if not _rpgrtl_skip_mode and active_src:
                                translated = _rpgrtl_lookup(active_src)
                                if translated and translated != active_src:
                                    _rpgrtl_force_text = translated
                                    _rpgrtl_force_update_current_text(_rpgrtl_wrap_font(translated))
                                    _rpgrtl_patch_active_widget("cache_hit", translated)
                            # Only apply force_text when it still matches the on-screen source
                            # (avoids pasting an older line onto a newer dialogue page).
                            force_ok = False
                            if force_text and (force_seq == 0 or force_seq != _rpgrtl_last_force_seq):
                                if not force_source:
                                    force_ok = True
                                elif active_src and (
                                    force_source == active_src
                                    or force_source in _rpgrtl_candidates(active_src)
                                    or active_src in _rpgrtl_candidates(force_source)
                                ):
                                    force_ok = True
                            if force_ok:
                                if force_seq:
                                    _rpgrtl_last_force_seq = force_seq
                                wrapped = _rpgrtl_wrap_font(force_text)
                                _rpgrtl_force_text = wrapped
                                _rpgrtl_debug("notify FORCE_TEXT received: " + repr(force_text[:100]))
                                _rpgrtl_log("force_text_received", {"target": force_text[:180], "force_seq": force_seq, "force_source": force_source[:120]})
                                if not _rpgrtl_skip_mode:
                                    _rpgrtl_force_update_current_text(wrapped)
                                    _rpgrtl_patch_active_widget("force_text", wrapped)
                            elif got_new_map and not _rpgrtl_skip_mode:
                                _rpgrtl_patch_active_widget("notify_refresh")
                                if active_src:
                                    translated = _rpgrtl_lookup(active_src)
                                    if translated and translated != active_src:
                                        _rpgrtl_force_update_current_text(_rpgrtl_wrap_font(translated))
                        else:
                            _rpgrtl_debug("notify response not dict: " + repr(type(notify_payload)))
                    except Exception as _notify_exc:
                        _rpgrtl_debug("notify EXCEPTION: " + repr(_notify_exc))
                except Exception as _loop_exc:
                    _rpgrtl_debug("loop EXCEPTION: " + repr(_loop_exc))
        threading.Thread(target=_update_loop, daemon=True).start()

    try:
        _rpgrtl_background_update()
    except Exception:
        pass

    # Boot log
    try:
        _rpgrtl_log("bridge_loaded", {"version": _rpgrtl_bridge_version, "gamedir": config.gamedir, "cache_count": len(_rpgrtl_translation_cache)})
        _rpgrtl_send("/boot", {"pid": os.getpid(), "root": config.gamedir, "version": renpy.version_only + " bridge " + _rpgrtl_bridge_version})
    except Exception:
        pass
