from __future__ import annotations

import re
import shutil
import json
import time
from pathlib import Path

from .models import DataRecord, ProjectInfo, TranslationEntry


STRING_PATTERN = re.compile(r'^\s*old\s+"(?P<old>(?:[^"\\]|\\.)*)"\s*$')
QUOTE_PATTERN = re.compile(
    r'^(?P<indent>\s*)(?P<speaker>[A-Za-z_][\w]*)?\s*"(?P<text>(?:[^"\\]|\\.)*)"(?:\s+.*)?$'
)
IDENTIFIER_PATTERN = re.compile(r"^[A-Za-z_][\w]*$")
RPA_TEXT_PATTERN = re.compile(rb"[\x20-\x7e\x80-\xff]{4,}")
RUNTIME_PATCH_NAME = "zz_rpgrtl_runtime_translation.rpy"
EMBEDDED_PATCH_NAME = "zz_rpgrtl_embedded_translation.rpy"
LANGUAGE_BOOTSTRAP_NAME = "zz_rpgrtl_language.rpy"
EXTRACTOR_NAME = "zz_rpgrtl_extract.rpy"
RESOURCE_PREP_NAME = "zz_rpgrtl_prepare_renpy.py"

RENPLY_RUNTIME_EXTRACTOR_SOURCE = r'''
# Auto-generated by RPGRenPyLocalizer.
# This file asks Ren'Py itself to export dialogue/string metadata from compiled scripts.
init 999 python:
    def _rpgrtl_export_texts():
        try:
            import os
            import json
            import renpy

            base_dir = os.path.dirname(config.gamedir)
            work_dir = os.path.join(base_dir, ".rpgrtl_workspace")
            if not os.path.isdir(work_dir):
                os.makedirs(work_dir)
            output = os.path.join(work_dir, "renpy_extracted.json")
            entries = []
            seen = set()

            def _clean(value):
                if value is None:
                    return ""
                try:
                    return str(value)
                except Exception:
                    return repr(value)

            def _add(category, source, file_name, context, line, identifier):
                source = _clean(source).strip()
                if not source:
                    return
                key = (category, _clean(file_name), _clean(context), source)
                if key in seen:
                    return
                seen.add(key)
                entries.append({
                    "category": category,
                    "source": source,
                    "file": _clean(file_name),
                    "context": _clean(context),
                    "line": int(line or 0),
                    "identifier": _clean(identifier),
                })

            translator = renpy.game.script.translator
            translate_say_type = getattr(renpy.ast, "TranslateSay", None)
            for filename, translates in getattr(translator, "file_translates", {}).items():
                for _label, translate_node in translates:
                    if translate_say_type is not None and isinstance(translate_node, translate_say_type):
                        block = [translate_node]
                    else:
                        block = getattr(translate_node, "block", []) or []
                    for node in block:
                        if isinstance(node, renpy.ast.Say):
                            _add(
                                "dialogue",
                                getattr(node, "what", ""),
                                getattr(translate_node, "filename", filename),
                                getattr(node, "who", "") or "narrator",
                                getattr(node, "linenumber", getattr(translate_node, "linenumber", 0)),
                                getattr(translate_node, "identifier", ""),
                            )

            try:
                strings = renpy.translation.scanstrings.scan(0, 2147483647, False)
                for item in strings:
                    _add(
                        "system",
                        getattr(item, "text", ""),
                        getattr(item, "filename", ""),
                        "string",
                        getattr(item, "line", 0),
                        getattr(item, "text", ""),
                    )
            except Exception as exc:
                entries.append({
                    "category": "system",
                    "source": "",
                    "file": "scanstrings",
                    "context": "error: %s" % exc,
                    "line": 0,
                    "identifier": "",
                })

            with open(output, "w", encoding="utf-8") as f:
                json.dump({"ok": True, "entries": entries}, f, ensure_ascii=False, indent=2)
            print("RPGRenPyLocalizer exported %d Ren'Py text entries to %s" % (len(entries), output))
        except Exception as exc:
            try:
                import os
                import json
                base_dir = os.path.dirname(config.gamedir)
                work_dir = os.path.join(base_dir, ".rpgrtl_workspace")
                if not os.path.isdir(work_dir):
                    os.makedirs(work_dir)
                with open(os.path.join(work_dir, "renpy_extracted.json"), "w", encoding="utf-8") as f:
                    json.dump({"ok": False, "error": str(exc), "entries": []}, f, ensure_ascii=False, indent=2)
            except Exception:
                pass

    try:
        config.start_callbacks.append(_rpgrtl_export_texts)
    except Exception:
        try:
            config.after_load_callbacks.append(_rpgrtl_export_texts)
        except Exception:
            _rpgrtl_export_texts()
'''


class RenPyService:
    def __init__(self, project: ProjectInfo) -> None:
        if not project.scripts_dir:
            raise ValueError("Ren'Py 项目缺少 game 脚本目录。")
        self.project = project
        self.scripts_dir = project.scripts_dir

    def extract_translations(self) -> list[TranslationEntry]:
        entries: list[TranslationEntry] = []
        entries.extend(self._extract_from_runtime_cache())
        for file_path in sorted(self._candidate_files()):
            if self._is_translation_file(file_path):
                entries.extend(self._extract_from_translation_file(file_path))
            else:
                entries.extend(self._extract_from_script_file(file_path))
        return self._deduplicate(entries)

    def runtime_export_path(self) -> Path:
        return self.project.root / ".rpgrtl_workspace" / "renpy_extracted.json"

    def install_runtime_extractor(self, clear_cache: bool = False) -> Path:
        path = self.scripts_dir / EXTRACTOR_NAME
        path.write_text(RENPLY_RUNTIME_EXTRACTOR_SOURCE.strip() + "\n", encoding="utf-8", newline="\n")
        if clear_cache:
            try:
                self.runtime_export_path().unlink()
            except FileNotFoundError:
                pass
        return path

    def needs_runtime_extraction(self) -> bool:
        if self.runtime_export_path().exists():
            return False
        source_files = [
            path
            for path in self.scripts_dir.rglob("*.rpy")
            if not self._is_translation_file(path) and not self._is_generated_file(path)
        ]
        compiled_or_archived = any(self.scripts_dir.rglob("*.rpyc")) or any(self.scripts_dir.rglob("*.rpa"))
        return compiled_or_archived and not source_files

    def can_runtime_extract(self) -> bool:
        return any(self.scripts_dir.rglob("*.rpyc")) or any(self.scripts_dir.rglob("*.rpa"))

    def prepare_source_tree(self) -> dict[str, int | str]:
        rpy_count = len(list(self.scripts_dir.rglob("*.rpy")))
        rpyc_files = list(self.scripts_dir.rglob("*.rpyc"))
        rpa_files = list(self.scripts_dir.rglob("*.rpa"))
        decompiled = 0
        extracted = 0
        if rpa_files:
            extracted += self._run_unrpa(rpa_files)
        if rpyc_files:
            decompiled += self._run_unrpyc(rpyc_files)
        return {
            "rpy": len(list(self.scripts_dir.rglob("*.rpy"))),
            "rpyc": len(list(self.scripts_dir.rglob("*.rpyc"))),
            "rpa": len(list(self.scripts_dir.rglob("*.rpa"))),
            "decompiled": decompiled,
            "extracted": extracted,
        }

    def _run_unrpa(self, archives: list[Path]) -> int:
        try:
            import unrpa  # type: ignore
        except Exception:
            return 0
        extracted = 0
        for archive in archives:
            try:
                out_dir = archive.parent
                result = getattr(unrpa, "extract", None)
                if callable(result):
                    result(str(archive), str(out_dir))
                else:
                    extractor = getattr(unrpa, "UnRPA", None)
                    if callable(extractor):
                        instance = extractor(str(archive))
                        if hasattr(instance, "extract"):
                            instance.extract(str(out_dir))
                        elif hasattr(instance, "unpack"):
                            instance.unpack(str(out_dir))
                        else:
                            continue
                    else:
                        continue
                extracted += 1
            except Exception:
                continue
        return extracted

    def _run_unrpyc(self, compiled_files: list[Path]) -> int:
        try:
            import unrpyc  # type: ignore
        except Exception:
            return 0
        decompiled = 0
        for compiled in compiled_files:
            try:
                runner = getattr(unrpyc, "decompile_rpyc", None)
                if callable(runner):
                    runner(str(compiled), None, overwrite=True)
                    decompiled += 1
            except Exception:
                continue
        return decompiled

    def apply_translations(self, translations: dict[str, TranslationEntry]) -> int:
        entries = [entry for entry in translations.values() if entry.target.strip()]
        replaced_ids = self._replace_script_sources(entries)
        fallback_entries = [entry for entry in entries if entry.entry_id not in replaced_ids]
        fallback_count = self._write_embedded_text_patch(fallback_entries)
        if fallback_count:
            self._write_translation_strings_file(fallback_entries)
            self._write_language_bootstrap()
        return len(replaced_ids) + fallback_count

    def build_runtime_translation_patch(self, translations: dict[str, TranslationEntry]) -> tuple[Path, int]:
        mapping = {
            entry.source: entry.target
            for entry in translations.values()
            if entry.source.strip() and entry.target.strip()
        }
        output = self.scripts_dir / RUNTIME_PATCH_NAME
        rendered_mapping = json.dumps(mapping, ensure_ascii=False, indent=4)
        rendered_mapping = rendered_mapping.replace("\n", "\n    ")
        lines = [
            "# Auto-generated temporary runtime translation patch.",
            "# Delete this file to disable temporary text replacement.",
            "init -999 python:",
            f"    _rpgrtl_runtime_translations = {rendered_mapping}",
            "    _rpgrtl_previous_replace_text = config.replace_text",
            "",
            "    def _rpgrtl_replace_text(s):",
            "        if not isinstance(s, str):",
            "            return s",
            "        original = s",
            "        if _rpgrtl_previous_replace_text is not None:",
            "            s = _rpgrtl_previous_replace_text(s)",
            "        return _rpgrtl_runtime_translations.get(",
            "            s,",
            "            _rpgrtl_runtime_translations.get(original, _rpgrtl_runtime_translations.get(s.strip(), s))",
            "        )",
            "",
            "    config.replace_text = _rpgrtl_replace_text",
        ]
        output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        return output, len(mapping)

    def _write_embedded_text_patch(self, entries: list[TranslationEntry]) -> int:
        mapping = {
            entry.source: entry.target
            for entry in entries
            if entry.source.strip() and entry.target.strip()
        }
        if not mapping:
            return 0
        output = self.scripts_dir / EMBEDDED_PATCH_NAME
        rendered_mapping = json.dumps(mapping, ensure_ascii=False, indent=4)
        rendered_mapping = rendered_mapping.replace("\n", "\n    ")
        lines = [
            "# Auto-generated permanent text replacement patch.",
            "# Delete this file to restore original display text for compiled-only Ren'Py scripts.",
            "init -999 python:",
            f"    _rpgrtl_embedded_translations = {rendered_mapping}",
            "    _rpgrtl_previous_replace_text = config.replace_text",
            "",
            "    def _rpgrtl_embedded_replace_text(s):",
            "        if not isinstance(s, str):",
            "            return s",
            "        original = s",
            "        if _rpgrtl_previous_replace_text is not None:",
            "            s = _rpgrtl_previous_replace_text(s)",
            "        return _rpgrtl_embedded_translations.get(",
            "            s,",
            "            _rpgrtl_embedded_translations.get(original, _rpgrtl_embedded_translations.get(s.strip(), s))",
            "        )",
            "",
            "    config.replace_text = _rpgrtl_embedded_replace_text",
        ]
        output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        return len(mapping)

    def _write_translation_strings_file(self, entries: list[TranslationEntry]) -> int:
        self._backup_translations()
        tl_dir = self.scripts_dir / "tl" / "schinese"
        tl_dir.mkdir(parents=True, exist_ok=True)
        output = tl_dir / "codex_generated.rpy"

        lines = [
            "# Auto-generated by RPGRenPyLocalizer",
            "translate schinese strings:",
            "",
        ]
        count = 0
        for entry in sorted(entries, key=lambda item: item.entry_id):
            if count % 500 == 0:
                time.sleep(0)
            escaped_source = self._escape(entry.source)
            escaped_target = self._escape(entry.target)
            lines.append(f"    # {entry.file} | {entry.context}")
            lines.append(f'    old "{escaped_source}"')
            lines.append(f'    new "{escaped_target}"')
            lines.append("")
            count += 1

        output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
        return count

    def _replace_script_sources(self, entries: list[TranslationEntry]) -> set[str]:
        self._backup_scripts()
        grouped: dict[Path, list[TranslationEntry]] = {}
        for entry in entries:
            if not entry.file.lower().endswith(".rpy"):
                continue
            file_path = self._resolve_script_file(entry.file)
            if not file_path:
                continue
            grouped.setdefault(file_path, []).append(entry)

        changed_ids: set[str] = set()
        for file_index, (file_path, file_entries) in enumerate(grouped.items()):
            if file_index % 3 == 0:
                time.sleep(0)
            lines = self._read_text_file(file_path).splitlines()
            changed = False
            for index, entry in enumerate(file_entries):
                if index % 500 == 0:
                    time.sleep(0)
                try:
                    line_index = int(entry.entry_id.rsplit("::", 1)[-1])
                except ValueError:
                    continue
                if line_index < 0 or line_index >= len(lines):
                    continue
                original = lines[line_index]
                match = QUOTE_PATTERN.match(original)
                if not match:
                    continue
                current_text = self._unescape(match.group("text"))
                if current_text != entry.source:
                    continue
                prefix = original[: match.start("text")]
                suffix = original[match.end("text") :]
                lines[line_index] = f"{prefix}{self._escape(entry.target)}{suffix}"
                changed_ids.add(entry.entry_id)
                changed = True
            if changed:
                file_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        return changed_ids

    def _resolve_script_file(self, file_name: str) -> Path | None:
        candidate = self.project.root / file_name
        if candidate.exists():
            return candidate
        candidate = self.scripts_dir / file_name
        if candidate.exists():
            return candidate
        matches = list(self.scripts_dir.rglob(Path(file_name).name))
        if len(matches) == 1:
            return matches[0]
        return None

    def _write_language_bootstrap(self) -> None:
        output = self.scripts_dir / LANGUAGE_BOOTSTRAP_NAME
        lines = [
            "# Auto-generated by RPGRenPyLocalizer",
            "init -999 python:",
            '    config.language = "schinese"',
        ]
        output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    def list_data_records(self) -> list[DataRecord]:
        records: list[DataRecord] = []
        for file_path in sorted(self._candidate_files()):
            if self._is_translation_file(file_path):
                continue
            if file_path.suffix.lower() != ".rpy":
                continue
            for index, line in enumerate(self._read_text_file(file_path).splitlines(), start=1):
                stripped = line.strip()
                if not stripped or stripped.startswith("#"):
                    continue
                match = QUOTE_PATTERN.match(line)
                if not match:
                    continue
                text = self._unescape(match.group("text"))
                if not text.strip():
                    continue
                speaker = match.group("speaker") or "narrator"
                records.append(
                    DataRecord(
                        record_id=f"{file_path.relative_to(self.project.root)}::{index}",
                        label=speaker,
                        value=text,
                        file=str(file_path.relative_to(self.project.root)),
                        category="Ren'Py 脚本对白",
                        location=f"line {index}",
                        line_number=index,
                    )
                )
        return records

    def _candidate_files(self) -> list[Path]:
        files: list[Path] = []
        for pattern in ("*.rpy", "*.rpyc"):
            files.extend(sorted(self.scripts_dir.rglob(pattern)))
        seen: dict[str, Path] = {}
        for file_path in files:
            if self._is_translation_file(file_path) or self._is_generated_file(file_path):
                continue
            seen.setdefault(str(file_path.resolve()), file_path)
        return list(seen.values())

    def update_record(self, record: DataRecord, new_value: str) -> None:
        self._backup_scripts()
        file_path = self.project.root / record.file
        lines = self._read_text_file(file_path).splitlines()
        if not record.line_number or record.line_number < 1 or record.line_number > len(lines):
            raise ValueError("无法定位要修改的 Ren'Py 行。")
        original = lines[record.line_number - 1]
        match = QUOTE_PATTERN.match(original)
        if not match:
            raise ValueError("目标行不是可直接编辑的对白/文本行。")
        prefix = original[: match.start("text")]
        suffix = original[match.end("text") :]
        lines[record.line_number - 1] = f"{prefix}{self._escape(new_value)}{suffix}"
        file_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    def _extract_from_translation_file(self, file_path: Path) -> list[TranslationEntry]:
        entries: list[TranslationEntry] = []
        lines = self._read_text_file(file_path).splitlines()
        current_old = ""
        for index, line in enumerate(lines):
            match_old = STRING_PATTERN.match(line)
            if match_old:
                current_old = self._unescape(match_old.group("old"))
                continue

            stripped = line.strip()
            if stripped.startswith("new ") and current_old:
                target = stripped[4:].strip()
                if target.startswith('"') and target.endswith('"'):
                    entries.append(
                        TranslationEntry(
                            entry_id=f"{file_path.name}::{index}",
                        source=current_old,
                        target=self._unescape(target[1:-1]),
                        file=file_path.name,
                        context="translation strings",
                        category="dialogue",
                    )
                )
                current_old = ""
        return entries

    def _extract_from_runtime_cache(self) -> list[TranslationEntry]:
        path = self.runtime_export_path()
        if not path.exists():
            return []
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return []
        if not payload.get("ok", False):
            return []
        entries: list[TranslationEntry] = []
        for index, item in enumerate(payload.get("entries", [])):
            if not isinstance(item, dict):
                continue
            source = str(item.get("source", "")).strip()
            if not source:
                continue
            file_name = str(item.get("file", "compiled"))
            context = str(item.get("context", ""))
            identifier = str(item.get("identifier", ""))
            line = item.get("line", 0)
            category = str(item.get("category", "dialogue") or "dialogue")
            entry_id = f"runtime::{file_name}::{identifier}::{line}::{index}"
            entries.append(
                TranslationEntry(
                    entry_id=entry_id,
                    source=source,
                    file=file_name or "compiled",
                    context=context,
                    category="dialogue" if category == "dialogue" else "system",
                )
            )
        return entries

    def _extract_from_script_file(self, file_path: Path) -> list[TranslationEntry]:
        entries: list[TranslationEntry] = []
        if file_path.suffix.lower() == ".rpyc":
            return self._extract_from_binary_file(file_path)
        for index, line in enumerate(self._read_text_file(file_path).splitlines()):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            match = QUOTE_PATTERN.match(line)
            if not match:
                continue
            text = self._unescape(match.group("text"))
            if not text.strip():
                continue
            speaker = match.group("speaker") or "narrator"
            entries.append(
                TranslationEntry(
                    entry_id=f"{file_path.name}::{index}",
                    source=text,
                    file=file_path.name,
                    context=speaker,
                    category="dialogue",
                )
            )
        return self._deduplicate(entries)

    def _extract_from_binary_file(self, file_path: Path) -> list[TranslationEntry]:
        entries: list[TranslationEntry] = []
        try:
            payload = file_path.read_bytes()
        except OSError:
            return entries
        seen: set[str] = set()
        for index, raw in enumerate(RPA_TEXT_PATTERN.findall(payload)):
            text = raw.decode("utf-8", errors="ignore").strip()
            text = text.replace("\\n", "\n").strip()
            if not self._looks_like_translatable_text(text) or text in seen:
                continue
            seen.add(text)
            entries.append(
                TranslationEntry(
                    entry_id=f"{file_path.name}::compiled::{index}",
                    source=text,
                    file=file_path.name,
                    context="compiled script",
                    category="dialogue",
                )
            )
        return entries

    @staticmethod
    def _is_translation_file(file_path: Path) -> bool:
        return "tl" in file_path.parts

    @staticmethod
    def _is_generated_file(file_path: Path) -> bool:
        return file_path.name in {RUNTIME_PATCH_NAME, EMBEDDED_PATCH_NAME, LANGUAGE_BOOTSTRAP_NAME, EXTRACTOR_NAME}

    @staticmethod
    def _read_text_file(file_path: Path) -> str:
        for encoding in ("utf-8-sig", "utf-8", "cp932", "gbk"):
            try:
                return file_path.read_text(encoding=encoding)
            except UnicodeDecodeError:
                continue
        return file_path.read_text(encoding="utf-8", errors="ignore")

    @staticmethod
    def _looks_like_translatable_text(text: str) -> bool:
        if len(text) < 2 or len(text) > 240:
            return False
        if text.startswith(("$", "#", "renpy.", "config.", "gui.")):
            return False
        if IDENTIFIER_PATTERN.match(text):
            return False
        return any("\u3040" <= char <= "\u30ff" or "\u4e00" <= char <= "\u9fff" or "a" <= char.lower() <= "z" for char in text)

    def _backup_translations(self) -> None:
        source = self.scripts_dir / "tl"
        if not source.exists():
            return
        backup_root = self.project.root / ".rpgrtl_backup" / "tl"
        if backup_root.exists():
            return
        shutil.copytree(source, backup_root)

    def _backup_scripts(self) -> None:
        backup_root = self.project.root / ".rpgrtl_backup" / "game"
        if backup_root.exists():
            return
        shutil.copytree(self.scripts_dir, backup_root, ignore=shutil.ignore_patterns("tl"))

    @staticmethod
    def _escape(value: str) -> str:
        return value.replace("\\", "\\\\").replace('"', '\\"')

    @staticmethod
    def _unescape(value: str) -> str:
        return value.replace('\\"', '"').replace("\\\\", "\\")

    @staticmethod
    def _deduplicate(entries: list[TranslationEntry]) -> list[TranslationEntry]:
        by_source: dict[str, TranslationEntry] = {}
        for entry in entries:
            by_source.setdefault(entry.source, entry)
        return list(by_source.values())
