from __future__ import annotations

import re
import shutil
from pathlib import Path

from .models import DataRecord, ProjectInfo, TranslationEntry


STRING_PATTERN = re.compile(r'^\s*old\s+"(?P<old>(?:[^"\\]|\\.)*)"\s*$')
QUOTE_PATTERN = re.compile(
    r'^(?P<indent>\s*)(?P<speaker>[A-Za-z_][\w]*)?\s*"(?P<text>(?:[^"\\]|\\.)*)"(?:\s+.*)?$'
)


class RenPyService:
    def __init__(self, project: ProjectInfo) -> None:
        if not project.scripts_dir:
            raise ValueError("Ren'Py 项目缺少 game 脚本目录。")
        self.project = project
        self.scripts_dir = project.scripts_dir

    def extract_translations(self) -> list[TranslationEntry]:
        entries: list[TranslationEntry] = []
        for file_path in sorted(self.scripts_dir.rglob("*.rpy")):
            if self._is_translation_file(file_path):
                entries.extend(self._extract_from_translation_file(file_path))
            else:
                entries.extend(self._extract_from_script_file(file_path))
        return entries

    def apply_translations(self, translations: dict[str, TranslationEntry]) -> int:
        self._backup_translations()
        tl_dir = self.scripts_dir / "tl" / "schinese"
        tl_dir.mkdir(parents=True, exist_ok=True)
        output = tl_dir / "codex_generated.rpy"

        entries = [entry for entry in translations.values() if entry.target.strip()]
        lines = [
            "# Auto-generated by RPGRenPyLocalizer",
            "translate schinese strings:",
            "",
        ]
        count = 0
        for entry in sorted(entries, key=lambda item: item.entry_id):
            escaped_source = self._escape(entry.source)
            escaped_target = self._escape(entry.target)
            lines.append(f"    # {entry.file} | {entry.context}")
            lines.append(f'    old "{escaped_source}"')
            lines.append(f'    new "{escaped_target}"')
            lines.append("")
            count += 1

        output.write_text("\n".join(lines), encoding="utf-8", newline="\n")
        return count

    def list_data_records(self) -> list[DataRecord]:
        records: list[DataRecord] = []
        for file_path in sorted(self.scripts_dir.rglob("*.rpy")):
            if self._is_translation_file(file_path):
                continue
            for index, line in enumerate(file_path.read_text(encoding="utf-8").splitlines(), start=1):
                stripped = line.strip()
                if not stripped or stripped.startswith("#"):
                    continue
                match = QUOTE_PATTERN.match(line)
                if not match:
                    continue
                text = self._unescape(match.group("text"))
                if not text.strip():
                    continue
                speaker = match.group("speaker") or "narrator"
                records.append(
                    DataRecord(
                        record_id=f"{file_path.relative_to(self.project.root)}::{index}",
                        label=speaker,
                        value=text,
                        file=str(file_path.relative_to(self.project.root)),
                        category="Ren'Py 脚本对白",
                        location=f"line {index}",
                        line_number=index,
                    )
                )
        return records

    def update_record(self, record: DataRecord, new_value: str) -> None:
        self._backup_scripts()
        file_path = self.project.root / record.file
        lines = file_path.read_text(encoding="utf-8").splitlines()
        if not record.line_number or record.line_number < 1 or record.line_number > len(lines):
            raise ValueError("无法定位要修改的 Ren'Py 行。")
        original = lines[record.line_number - 1]
        match = QUOTE_PATTERN.match(original)
        if not match:
            raise ValueError("目标行不是可直接编辑的对白/文本行。")
        prefix = original[: match.start("text")]
        suffix = original[match.end("text") :]
        lines[record.line_number - 1] = f"{prefix}{self._escape(new_value)}{suffix}"
        file_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")

    def _extract_from_translation_file(self, file_path: Path) -> list[TranslationEntry]:
        entries: list[TranslationEntry] = []
        lines = file_path.read_text(encoding="utf-8").splitlines()
        current_old = ""
        for index, line in enumerate(lines):
            match_old = STRING_PATTERN.match(line)
            if match_old:
                current_old = self._unescape(match_old.group("old"))
                continue

            stripped = line.strip()
            if stripped.startswith("new ") and current_old:
                target = stripped[4:].strip()
                if target.startswith('"') and target.endswith('"'):
                    entries.append(
                        TranslationEntry(
                            entry_id=f"{file_path.name}::{index}",
                        source=current_old,
                        target=self._unescape(target[1:-1]),
                        file=file_path.name,
                        context="translation strings",
                        category="dialogue",
                    )
                )
                current_old = ""
        return entries

    def _extract_from_script_file(self, file_path: Path) -> list[TranslationEntry]:
        entries: list[TranslationEntry] = []
        for index, line in enumerate(file_path.read_text(encoding="utf-8").splitlines()):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            match = QUOTE_PATTERN.match(line)
            if not match:
                continue
            text = self._unescape(match.group("text"))
            if not text.strip():
                continue
            speaker = match.group("speaker") or "narrator"
            entries.append(
                TranslationEntry(
                    entry_id=f"{file_path.name}::{index}",
                    source=text,
                    file=file_path.name,
                    context=speaker,
                    category="dialogue",
                )
            )
        return self._deduplicate(entries)

    @staticmethod
    def _is_translation_file(file_path: Path) -> bool:
        return "tl" in file_path.parts

    def _backup_translations(self) -> None:
        source = self.scripts_dir / "tl"
        if not source.exists():
            return
        backup_root = self.project.root / ".rpgrtl_backup" / "tl"
        if backup_root.exists():
            return
        shutil.copytree(source, backup_root)

    def _backup_scripts(self) -> None:
        backup_root = self.project.root / ".rpgrtl_backup" / "game"
        if backup_root.exists():
            return
        shutil.copytree(self.scripts_dir, backup_root, ignore=shutil.ignore_patterns("tl"))

    @staticmethod
    def _escape(value: str) -> str:
        return value.replace("\\", "\\\\").replace('"', '\\"')

    @staticmethod
    def _unescape(value: str) -> str:
        return value.replace('\\"', '"').replace("\\\\", "\\")

    @staticmethod
    def _deduplicate(entries: list[TranslationEntry]) -> list[TranslationEntry]:
        by_source: dict[str, TranslationEntry] = {}
        for entry in entries:
            by_source.setdefault(entry.source, entry)
        return list(by_source.values())
