"""Unity runtime bridge inspired by XUnity.AutoTranslator.

XUA already solves in-process text hooks (UGUI / TMP / NGUI / IMGUI / TextAsset).
We do not reimplement those hooks. Instead we:

1. Write XUA-compatible translation dictionaries (``original=translation``).
2. Generate an XUA / BepInEx install layout with ``Endpoint=CustomTranslate``
   pointing at a local HTTP endpoint.
3. Serve that CustomTranslate API (``GET ?from=&to=&text=`` → plain string)
   and optionally capture untranslated strings for the workbench.

Reference: ``其他/XUnity.AutoTranslator-master`` (MIT).
"""

from __future__ import annotations

import json
import re
import threading
import urllib.parse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

from .models import ProjectInfo, TranslationEntry

# XUA CustomTranslate-style live port (distinct from Ren'Py 32180 / RM 32181 / Wolf WS 35421).
XUA_LIVE_PORT = 32182

XUA_TRANSLATION_REL = Path("AutoTranslator") / "Translation" / "zh-CN" / "Text"
XUA_MANUAL_FILE = "RPGRenPyLocalizer.txt"
XUA_AUTO_FILE = "_AutoGeneratedTranslations.txt"

_COMMENT_RE = re.compile(r"^\s*(//|#|;)")


def encode_xua_text(text: str) -> str:
    """Escape a single side of an XUA ``key=value`` line (TextHelper.Encode)."""
    out = (text or "").replace("\\", "\\\\")
    out = out.replace("=", "\\=")
    return out.replace("\r", "\\r").replace("\n", "\\n")


def decode_xua_segment(text: str) -> str:
    if text is None:
        return ""
    out: list[str] = []
    i = 0
    n = len(text)
    while i < n:
        ch = text[i]
        if ch != "\\":
            out.append(ch)
            i += 1
            continue
        i += 1
        if i >= n:
            out.append("\\")
            break
        esc = text[i]
        if esc in ("=", "\\"):
            out.append(esc)
        elif esc == "n":
            out.append("\n")
        elif esc == "r":
            out.append("\r")
        elif esc == "u" and i + 4 < n:
            try:
                out.append(chr(int(text[i + 1 : i + 5], 16)))
                i += 4
            except ValueError:
                out.append("\\u")
        else:
            out.append("\\")
            out.append(esc)
        i += 1
    return "".join(out)


def parse_xua_line(line: str) -> tuple[str, str] | None:
    """Parse one XUA translation line into (source, target). Returns None for junk."""
    raw = (line or "").strip("\r\n")
    if not raw.strip() or _COMMENT_RE.match(raw):
        return None
    parts: list[str] = []
    buf: list[str] = []
    i = 0
    n = len(raw)
    while i < n:
        ch = raw[i]
        if ch == "\\" and i + 1 < n:
            buf.append(ch)
            buf.append(raw[i + 1])
            i += 2
            continue
        if ch == "=":
            parts.append("".join(buf))
            buf = []
            i += 1
            continue
        buf.append(ch)
        i += 1
    parts.append("".join(buf))
    if len(parts) < 2:
        return None
    source = decode_xua_segment(parts[0])
    target = decode_xua_segment(parts[1])
    if not source.strip():
        return None
    return source, target


def format_xua_line(source: str, target: str) -> str:
    return f"{encode_xua_text(source)}={encode_xua_text(target)}"


def read_xua_translation_file(path: Path) -> list[tuple[str, str]]:
    if not path.is_file():
        return []
    text = path.read_text(encoding="utf-8-sig", errors="replace")
    pairs: list[tuple[str, str]] = []
    for line in text.splitlines():
        parsed = parse_xua_line(line)
        if parsed:
            pairs.append(parsed)
    return pairs


def write_xua_translation_file(path: Path, pairs: list[tuple[str, str]]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Auto-generated by RPGRenPyLocalizer (XUA format).",
        "// Reload in-game with XUA ALT+R after editing.",
        "",
    ]
    for source, target in pairs:
        if source.strip() and target.strip() and source != target:
            lines.append(format_xua_line(source, target))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return path


def export_entries_to_xua(entries: list[TranslationEntry] | dict[str, TranslationEntry], target: Path) -> Path:
    values = list(entries.values()) if isinstance(entries, dict) else list(entries)
    pairs = [
        (entry.source, entry.target)
        for entry in values
        if entry.source.strip() and entry.target.strip() and entry.source != entry.target
    ]
    return write_xua_translation_file(target, pairs)


def import_xua_to_entries(path: Path, category: str = "unity_xua") -> list[TranslationEntry]:
    entries: list[TranslationEntry] = []
    for index, (source, target) in enumerate(read_xua_translation_file(path)):
        entries.append(
            TranslationEntry(
                entry_id=f"unity_xua::{path.name}::{index}",
                source=source,
                target=target,
                file=path.name,
                context=f"unity-xua;file={urllib.parse.quote(path.name, safe='')};row={index}",
                category=category,
            )
        )
    return entries


def build_xua_config(
    translate_url: str,
    from_language: str = "ja",
    to_language: str = "zh-CN",
    enable_imgui: bool = True,
    text_getter_compat: bool = True,
) -> str:
    """XUA Config.ini body wired to CustomTranslate (local RPGRenPyLocalizer)."""
    return (
        "[General]\n"
        "Endpoint=CustomTranslate\n"
        "FallbackEndpoint=\n"
        f"Language={to_language}\n"
        f"FromLanguage={from_language}\n"
        "HandleRichText=True\n"
        "IgnoreWhitespaceInDialogue=True\n"
        "SaveTextBetweenChunks=True\n"
        "RedirectedResourceOutputPath=ResourceRedirected\n"
        "TextureDirectory=Textures\n"
        "TextureHashGenerationStrategy=FromImageData\n"
        "EnableUIResizing=False\n"
        "EnableIMGUI=%s\n"
        "TextGetterCompatibilityMode=%s\n"
        "GeneratePartialTranslations=False\n"
        "AutoGenerateTranslations=True\n"
        "OutputFile=Translation\\{Lang}\\Text\\_AutoGeneratedTranslations.txt\n"
        "\n"
        "[Custom]\n"
        "Url=%s\n"
        "EnableShortDelay=True\n"
        "DisableSpamChecks=True\n"
        "\n"
        "[Http]\n"
        "UserAgent=\n"
        "DisableCertificateValidation=True\n"
        "\n"
        "[Behaviour]\n"
        "ForceMonoModHooks=False\n"
        "IgnoreResourceLoadingErrors=True\n"
        % (
            "True" if enable_imgui else "False",
            "True" if text_getter_compat else "False",
            translate_url.rstrip("?"),
        )
    )


def xua_install_notes(il2cpp: bool = False) -> str:
    host = "BepInEx 6 IL2CPP + XUnity.AutoTranslator-BepInEx-IL2CPP" if il2cpp else "BepInEx 5 + XUnity.AutoTranslator-BepInEx（或 ReiPatcher 独立包）"
    return (
        "# RPGRenPyLocalizer × XUnity AutoTranslator\n\n"
        "本目录已写入 XUA 兼容的翻译文件与 Config.ini。\n\n"
        "## 安装运行时 Hook（一次性）\n\n"
        f"1. 在隔离副本中安装 **{host}**。\n"
        "2. 确认插件加载后会读取本目录 `AutoTranslator/`。\n"
        "3. 启动 RPGRenPyLocalizer 的 Unity 实时桥（CustomTranslate 端点）。\n"
        "4. 完整重启游戏。新文本会自动请求本地 API，译文写回 UI。\n\n"
        "## 翻译文件\n\n"
        f"- 人工/批量译文：`{XUA_TRANSLATION_REL.as_posix()}/{XUA_MANUAL_FILE}`（`原文=译文`）\n"
        f"- 运行时捕获：`{XUA_TRANSLATION_REL.as_posix()}/{XUA_AUTO_FILE}`（XUA 自动追加）\n"
        "- 游戏内 ALT+R 可热重载词典。\n\n"
        "## 能力边界\n\n"
        "- Hook 覆盖 UGUI Text / TextMeshPro / TextMesh / NGUI / IMGUI / TextAsset（Mono 更全）。\n"
        "- IL2CPP 依赖 BepInEx6 + 对应 IL2CPP 包，能力弱于 Mono。\n"
        "- AssetBundle 内文本需 ResourceRedirector / AssetStudio 导出后再写回，本桥不直接改二进制包。\n"
    )


def detect_unity_il2cpp(root: Path) -> bool:
    game_dir = root if (root / "GameAssembly.dll").is_file() else None
    if not game_dir:
        for child in root.iterdir() if root.is_dir() else []:
            if child.is_file() and child.name.lower() == "gameassembly.dll":
                game_dir = root
                break
    if (root / "GameAssembly.dll").is_file():
        return True
    for data in root.glob("*_Data"):
        if (data / "il2cpp_data").is_dir() or (data / "Metadata" / "global-metadata.dat").is_file():
            return True
    return False


class UnityXuaService:
    """Install XUA dictionaries/config and manage CustomTranslate capture."""

    def __init__(self, project: ProjectInfo):
        self.project = project

    @property
    def translation_dir(self) -> Path:
        return self.project.root / XUA_TRANSLATION_REL

    @property
    def manual_path(self) -> Path:
        return self.translation_dir / XUA_MANUAL_FILE

    @property
    def auto_path(self) -> Path:
        return self.translation_dir / XUA_AUTO_FILE

    @property
    def config_path(self) -> Path:
        return self.project.root / "AutoTranslator" / "Config" / "Config.ini"

    def live_url(self, port: int = XUA_LIVE_PORT) -> str:
        return f"http://127.0.0.1:{port}/xua/translate"

    def install_runtime_bridge(self, target_dir: Path | None = None) -> Path:
        dest = target_dir or self.project.root
        dest = Path(dest)
        trans_dir = dest / XUA_TRANSLATION_REL
        trans_dir.mkdir(parents=True, exist_ok=True)
        manual = trans_dir / XUA_MANUAL_FILE
        if not manual.is_file():
            write_xua_translation_file(manual, [])
        auto = trans_dir / XUA_AUTO_FILE
        if not auto.is_file():
            write_xua_translation_file(auto, [])
        config = dest / "AutoTranslator" / "Config" / "Config.ini"
        config.parent.mkdir(parents=True, exist_ok=True)
        config.write_text(
            build_xua_config(self.live_url()),
            encoding="utf-8",
            newline="\n",
        )
        notes = dest / "RPGRenPyLocalizer_Unity_XUA.md"
        notes.write_text(xua_install_notes(detect_unity_il2cpp(dest)), encoding="utf-8", newline="\n")
        return notes

    def export_translations(self, translations: dict[str, TranslationEntry]) -> Path:
        self.translation_dir.mkdir(parents=True, exist_ok=True)
        return export_entries_to_xua(translations, self.manual_path)

    def import_runtime_captures(self) -> list[TranslationEntry]:
        entries: list[TranslationEntry] = []
        for path in (self.auto_path, self.manual_path):
            entries.extend(import_xua_to_entries(path))
        return entries

    def lookup(self, source: str) -> str | None:
        for path in (self.manual_path, self.auto_path):
            for src, tgt in read_xua_translation_file(path):
                if src == source and tgt.strip() and src != tgt:
                    return tgt
        return None


_XUA_LIVE_STATE: dict[str, object] = {
    "translations": {},
    "seen": {},
    "events": [],
    "pre_translate_queue": [],
    "current_source": "",
    "xua_hit": 0,
    "xua_miss": 0,
    "seeded_last": 0,
    "idle_prefetch_count": 0,
    "notify_seq": 0,
    "service": None,
    "translator": None,
    "lastSeenAt": 0.0,
}
_XUA_LIVE_LOCK = threading.RLock()
_XUA_LIVE_SERVER: ThreadingHTTPServer | None = None


def configure_live_translator(callable_fn) -> None:
    """callable(source, source_lang, target_lang) -> str"""
    with _XUA_LIVE_LOCK:
        _XUA_LIVE_STATE["translator"] = callable_fn


def merge_live_translations(pairs: dict[str, str]) -> int:
    with _XUA_LIVE_LOCK:
        store: dict[str, str] = _XUA_LIVE_STATE.setdefault("translations", {})  # type: ignore[assignment]
        changed = 0
        for source, target in pairs.items():
            if source.strip() and target.strip() and source != target:
                store[source] = target
                changed += 1
        return changed


def live_translations() -> dict[str, str]:
    with _XUA_LIVE_LOCK:
        return dict(_XUA_LIVE_STATE.get("translations") or {})


def live_status() -> dict[str, object]:
    with _XUA_LIVE_LOCK:
        seen: dict[str, int] = _XUA_LIVE_STATE.setdefault("seen", {})  # type: ignore[assignment]
        store: dict[str, str] = _XUA_LIVE_STATE.setdefault("translations", {})  # type: ignore[assignment]
        last_seen = float(_XUA_LIVE_STATE.get("lastSeenAt") or 0.0)
        return {
            "running": _XUA_LIVE_SERVER is not None,
            "connected": bool(last_seen),
            "port": XUA_LIVE_PORT,
            "seen": len(seen),
            "translated": len(store),
            "translation_count": len(store),
            "queue_count": len(_XUA_LIVE_STATE.get("pre_translate_queue") or []),  # type: ignore[arg-type]
            "current_source": str(_XUA_LIVE_STATE.get("current_source") or ""),
            "xua_hit": int(_XUA_LIVE_STATE.get("xua_hit") or 0),
            "xua_miss": int(_XUA_LIVE_STATE.get("xua_miss") or 0),
            "seeded_last": int(_XUA_LIVE_STATE.get("seeded_last") or 0),
            "idle_prefetch_count": int(_XUA_LIVE_STATE.get("idle_prefetch_count") or 0),
            "events": len(_XUA_LIVE_STATE.get("events") or []),  # type: ignore[arg-type]
            "lastSeenAt": last_seen,
        }


def read_live_events(limit: int = 20) -> list[dict[str, object]]:
    with _XUA_LIVE_LOCK:
        events = list(_XUA_LIVE_STATE.get("events") or [])  # type: ignore[arg-type]
    if limit <= 0:
        return events
    return events[-limit:]


def _append_event(kind: str, source: str, target: str = "") -> None:
    events: list[dict[str, object]] = _XUA_LIVE_STATE.setdefault("events", [])  # type: ignore[assignment]
    events.append({"kind": kind, "source": source[:500], "target": target[:500]})
    if len(events) > 500:
        del events[:-500]


def _mark_seen(source: str) -> None:
    import time as _time

    seen: dict[str, int] = _XUA_LIVE_STATE.setdefault("seen", {})  # type: ignore[assignment]
    if source not in seen:
        seen[source] = 1
        _append_event("seen", source)
    _XUA_LIVE_STATE["current_source"] = source
    _XUA_LIVE_STATE["lastSeenAt"] = _time.time()


class _XuaCustomTranslateHandler(BaseHTTPRequestHandler):
    server_version = "RPGRenPyXuaBridge/1.0"

    def log_message(self, format: str, *args: object) -> None:  # noqa: A002
        return

    def _send_text(self, status: int, body: str) -> None:
        data = body.encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "text/plain; charset=utf-8")
        self.send_header("Content-Length", str(len(data)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(data)

    def _send_json(self, status: int, payload: dict) -> None:
        data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(data)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(data)

    def do_GET(self) -> None:  # noqa: N802
        parsed = urllib.parse.urlparse(self.path)
        if parsed.path not in {"/xua/translate", "/translate"}:
            self._send_json(404, {"ok": False, "error": "not found"})
            return
        query = urllib.parse.parse_qs(parsed.query)
        source = (query.get("text") or [""])[0]
        source_lang = (query.get("from") or [""])[0]
        target_lang = (query.get("to") or [""])[0]
        if not source.strip():
            self._send_text(200, source)
            return

        with _XUA_LIVE_LOCK:
            _mark_seen(source)
            store: dict[str, str] = _XUA_LIVE_STATE.setdefault("translations", {})  # type: ignore[assignment]
            if source in store and store[source].strip():
                _XUA_LIVE_STATE["xua_hit"] = int(_XUA_LIVE_STATE.get("xua_hit") or 0) + 1
                _append_event("hit", source, store[source])
                self._send_text(200, store[source])
                return
            service = _XUA_LIVE_STATE.get("service")

        if service is not None:
            hit = service.lookup(source)  # type: ignore[attr-defined]
            if hit:
                with _XUA_LIVE_LOCK:
                    store[source] = hit  # type: ignore[index]
                    _XUA_LIVE_STATE["xua_hit"] = int(_XUA_LIVE_STATE.get("xua_hit") or 0) + 1
                    _append_event("hit", source, hit)
                self._send_text(200, hit)
                return

        # Do not block Unity's render thread on AI. Queue the miss as urgent;
        # the shared live worker fills the cache for the next lookup.
        with _XUA_LIVE_LOCK:
            queue: list[str] = _XUA_LIVE_STATE.setdefault("pre_translate_queue", [])  # type: ignore[assignment]
            if source not in queue:
                queue.insert(0, source)
                del queue[1000:]
            _XUA_LIVE_STATE["xua_miss"] = int(_XUA_LIVE_STATE.get("xua_miss") or 0) + 1
            _append_event("miss", source)
        self._send_text(200, source)


def start_live_bridge_server(service: UnityXuaService | None = None, clear_seen: bool = False) -> dict[str, object]:
    global _XUA_LIVE_SERVER
    with _XUA_LIVE_LOCK:
        _XUA_LIVE_STATE["service"] = service
        if clear_seen:
            _XUA_LIVE_STATE["seen"] = {}
            _XUA_LIVE_STATE["events"] = []
            _XUA_LIVE_STATE["pre_translate_queue"] = []
            _XUA_LIVE_STATE["current_source"] = ""
            _XUA_LIVE_STATE["xua_hit"] = 0
            _XUA_LIVE_STATE["xua_miss"] = 0
            _XUA_LIVE_STATE["seeded_last"] = 0
            _XUA_LIVE_STATE["idle_prefetch_count"] = 0
        if _XUA_LIVE_SERVER is not None:
            return live_status()
        try:
            _XUA_LIVE_SERVER = ThreadingHTTPServer(("127.0.0.1", XUA_LIVE_PORT), _XuaCustomTranslateHandler)
        except OSError as exc:
            raise RuntimeError(f"Unity XUA 本地端口 {XUA_LIVE_PORT} 被占用或无法启动：{exc}") from exc
        thread = threading.Thread(target=_XUA_LIVE_SERVER.serve_forever, name="unity-xua-live", daemon=True)
        thread.start()
    return live_status()


def stop_live_bridge_server() -> dict[str, object]:
    global _XUA_LIVE_SERVER
    with _XUA_LIVE_LOCK:
        server = _XUA_LIVE_SERVER
        _XUA_LIVE_SERVER = None
        _XUA_LIVE_STATE["lastSeenAt"] = 0.0
    if server is not None:
        server.shutdown()
        server.server_close()
    return live_status()

